import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";
import { PrintableLearnersReport } from "@/components/reports/printable-learners-report";
import {
  REPORT_BOTTOM_LOGO_SOURCES,
  REPORT_TOP_LOGO_SOURCE,
  SIGNATURE_CAPTION,
} from "@/lib/reports/report-frame";
import type { PrintableReportLearner } from "@/lib/actions/export-learners";

afterEach(cleanup);

const learner: PrintableReportLearner = {
  id: "l1",
  fullName: "Dela Cruz, Juan",
  age: 8,
  gender: "MALE",
  englishReadingProfile: null,
  filipinoReadingProfile: "FULL_ALPHABET_KNOWLEDGE",
  isAralLearner: true,
  gradeLevel: { type: "GRADE_2" },
  section: { name: "Narra" },
};

const baseProps = {
  schoolName: "Sample Elementary School",
  generatedAt: new Date("2026-09-01T00:00:00Z"),
  learners: [learner],
  aralCount: 1,
  byGrade: [{ type: "GRADE_2", learners: [learner] }],
};

describe("PrintableLearnersReport DepEd print template", () => {
  it("renders the seal above the Republic/DepEd lines and the school name, even with no header", () => {
    render(<PrintableLearnersReport {...baseProps} />);

    const seal = screen.getByRole("img", { name: REPORT_TOP_LOGO_SOURCE.alt });
    expect(seal.getAttribute("src")).toBe(REPORT_TOP_LOGO_SOURCE.src);
    expect(screen.getByText("Republic of the Philippines")).toBeTruthy();
    expect(screen.getByText("DEPARTMENT OF EDUCATION")).toBeTruthy();
    // Bold school-name line, always present regardless of `header`.
    expect(screen.getByText("Sample Elementary School")).toBeTruthy();
    // No region/division/district data was supplied, so those lines are omitted.
    expect(screen.queryByText(/Schools Division of/)).toBeNull();
  });

  it("prefixes Region/Division/District from the header fields when supplied", () => {
    render(
      <PrintableLearnersReport
        {...baseProps}
        header={[
          { label: "School ID", value: "123456" },
          { label: "School Name", value: "Sample Elementary School" },
          { label: "Region", value: "Region IV-A" },
          { label: "Division", value: "Batangas" },
          { label: "District", value: "District 1" },
          { label: "School Year", value: "2026-2027" },
          { label: "Grade / Section", value: "Grade 2 - Narra" },
          { label: "Prepared by", value: "Juana Dela Cruz" },
        ]}
      />
    );

    expect(screen.getByText("Schools Division of Batangas")).toBeTruthy();
  });

  it("renders the uppercase report title above the tables", () => {
    render(<PrintableLearnersReport {...baseProps} subtitle="Grade 2 - Narra" />);
    const title = screen.getByRole("heading", { level: 1 });
    expect(title.textContent).toBe("Learner & ARAL Summary Report — Grade 2 - Narra");
    expect(title.className).toContain("uppercase");
  });

  it("renders the three signature columns with their captions, and the bottom logos in order", () => {
    render(
      <PrintableLearnersReport
        {...baseProps}
        footer={{ preparedBy: "Juana Dela Cruz", notedBy: "Maria Santos" }}
      />
    );

    expect(screen.getByText("Prepared by:")).toBeTruthy();
    expect(screen.getByText("Checked by:")).toBeTruthy();
    expect(screen.getByText("Noted by:")).toBeTruthy();
    expect(screen.getByText("Juana Dela Cruz")).toBeTruthy();
    expect(screen.getByText("Maria Santos")).toBeTruthy();
    expect(screen.getAllByText(SIGNATURE_CAPTION)).toHaveLength(3);

    const bottomLogos = REPORT_BOTTOM_LOGO_SOURCES.map((logo) =>
      screen.getByRole("img", { name: logo.alt })
    );
    // Same left-to-right order the wordmark/Bagong Pilipinas/division logos load in.
    for (let i = 0; i < bottomLogos.length; i++) {
      expect(bottomLogos[i]!.getAttribute("src")).toBe(REPORT_BOTTOM_LOGO_SOURCES[i]!.src);
    }

    expect(screen.getByText(/Generated by Juana Dela Cruz on/)).toBeTruthy();
  });

  it("renders fine without header or footer (older data shape)", () => {
    render(<PrintableLearnersReport {...baseProps} />);

    expect(screen.getByText("Sample Elementary School")).toBeTruthy();
    expect(screen.queryByText("Prepared by:")).toBeNull();
    expect(screen.queryByText(SIGNATURE_CAPTION)).toBeNull();
  });
});
