-- Enable Row Level Security on every table so none is exposed to the Supabase
-- anon/authenticated roles through PostgREST. Additive and idempotent: enabling
-- RLS twice is harmless, and no policy is created, changed or dropped. The app
-- reads and writes only through Prisma (service connection), which is unaffected.

ALTER TABLE "School" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SystemSetting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TermSubjectDefault" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SchoolYear" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TermWindowOverride" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DistrictAdminAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SchoolHeadProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeacherProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeacherInvite" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GradeLevel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Section" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeacherSection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Enrollment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Learner" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Announcement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AralProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AralMosyDecision" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AttendanceDayMeta" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReadingLevelRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TermSubject" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TermGrade" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "KinderCompetencyRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Report" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SupportTicket" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UnlockGrant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SchoolUnlockGrant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatChannel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatMention" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatRead" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ErrorEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_TeacherGrades" ENABLE ROW LEVEL SECURITY;
