import "server-only";

import type { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { teacherGradeScope, teacherLearnerScope } from "@/lib/teachers/scope";
import {
  ATTENDANCE_STATUS_LABELS,
  GRADE_LEVEL_LABELS,
  READING_PROFILE_LABELS,
  TERM_PERIOD_LABELS,
  WEEKLY_READING_COMPREHENSION_LEVEL_LABELS,
  WEEKLY_WORD_RECOGNITION_LEVEL_LABELS,
  WEEKLY_WRITING_LEVEL_LABELS,
} from "@/lib/constants/enum-labels";
import { formatLocalDateKey, parseLocalDateKey, schoolToday } from "@/lib/date-keys";
import { formatListingNameFromRecord } from "@/lib/names";
import { subjectNameKey } from "@/lib/terms/subjects";
import {
  capGridKeys,
  capNote,
  enumerateMonthStarts,
  enumerateWeekdays,
  resolveDateRange,
  unionDateKeys,
} from "@/lib/reports/grid";
import {
  rowGeneralAverage,
  termCellText,
  type TermCell,
} from "@/lib/terms/grading-scale";
import { isReadingRecordComplete } from "@/lib/reading/policy";
import {
  buildMosyBlocks,
  describeMosyWindowNote,
  type MosyLearner,
  type MosyWindowInfo,
} from "@/lib/reports/mosy";
import { resolveMosyWindow } from "@/lib/reports/mosy-window";
import { buildSf2Blocks, groupBySex, type Sf2Learner, type Sf2Status } from "@/lib/reports/sf2";
import type { TermPeriodValue } from "@/lib/terms/windows";
import type { ReportFilters } from "@/lib/reports/kinds";
import type { ReportHeaderField, ReportTable } from "@/lib/reports/render";

/**
 * The data half of the Reports Hub: one builder per report kind, each returning
 * the same `ReportTable` so `render.ts` can emit Excel or PDF without knowing
 * what it is looking at.
 *
 * TENANCY. Every builder receives an already-resolved `scope` and must spread
 * its `learnerWhere` / `gradeWhere` into its own `where`. The scope is built
 * once, in `reportScope()` below, from the signed-in user — a builder never
 * reads the session itself, so there is exactly one place a tenant predicate
 * could go missing rather than five.
 */

export type ReportScope = {
  schoolId: string;
  /** Set only for a real TEACHER; a Super Admin viewing a school is not one. */
  teacherId: string | null;
  schoolName: string;
  actorName: string;
};

export function reportScope(args: ReportScope): ReportScope {
  return args;
}

/**
 * A `ReportTable` plus the ids/counts the audit row should carry for this
 * kind, when the builder knows something the action cannot re-derive.
 *
 * MOSY resolves its own date window from the school year and its term
 * overrides, so `generateReport` has no way to name the window it exported
 * unless the builder hands it over. Carried here rather than widening
 * `ReportTable` (`render.ts`) because it is audit data, not render data, and
 * the renderers must stay unaware of it. Counts, keys and ids only — never a
 * learner field (`src/lib/audit.ts`).
 */
export type ReportAuditMeta = Record<string, string | number | null>;

export type ReportTableWithAudit = ReportTable & { auditMeta?: ReportAuditMeta };

/** Learner rows this actor may see at all, before the hub's own filters. */
function learnerWhere(
  scope: ReportScope,
  filters: ReportFilters
): Prisma.LearnerWhereInput {
  return {
    schoolId: scope.schoolId,
    deletedAt: null,
    archivedAt: null,
    ...(scope.teacherId ? teacherLearnerScope(scope.teacherId) : {}),
    ...(filters.gradeLevelId ? { gradeLevelId: filters.gradeLevelId } : {}),
    ...(filters.sectionId ? { sectionId: filters.sectionId } : {}),
  };
}

/** Grade rows this actor may see, used by the summary report. */
function gradeWhere(scope: ReportScope): Prisma.GradeLevelWhereInput {
  return {
    schoolId: scope.schoolId,
    deletedAt: null,
    ...(scope.teacherId ? teacherGradeScope(scope.teacherId) : {}),
  };
}

/**
 * `from`/`to` as an inclusive day range on a `@db.Date` column.
 *
 * `to` becomes `lt: to + 1 day` rather than `lte: to`: a `@db.Date` column
 * compares against local midnight, so `lte` would still include the whole of
 * `to` here but breaks the moment the column becomes a timestamp. Written as a
 * half-open range it is correct either way.
 */
function dateRange(filters: ReportFilters): { gte?: Date; lt?: Date } | undefined {
  const range: { gte?: Date; lt?: Date } = {};
  if (filters.from) range.gte = parseLocalDateKey(filters.from);
  if (filters.to) {
    const to = parseLocalDateKey(filters.to);
    range.lt = new Date(to.getFullYear(), to.getMonth(), to.getDate() + 1);
  }
  return range.gte || range.lt ? range : undefined;
}

function subtitleFor(
  scope: ReportScope,
  filters: ReportFilters,
  extra: string[] = []
): string[] {
  const parts: string[] = [scope.schoolName];
  if (filters.from || filters.to) {
    parts.push(`Range: ${filters.from ?? "start"} to ${filters.to ?? "today"}`);
  }
  return [
    ...parts,
    ...extra,
    `Generated by ${scope.actorName} on ${formatLocalDateKey(new Date())}`,
  ];
}

/**
 * `subtitleFor` without its own `Range:` line — used by the two grid builders
 * below, which resolve their own range (`resolveDateRange`, `./grid.ts`) and
 * pass it as an explicit extra line so a partial filter (only `from`, or
 * neither) does not print two disagreeing range summaries.
 */
function subtitleForGrid(scope: ReportScope, extra: string[] = []): string[] {
  return [
    scope.schoolName,
    ...extra,
    `Generated by ${scope.actorName} on ${formatLocalDateKey(new Date())}`,
  ];
}

/**
 * "the caller's active school year", read once here and shared by the two
 * grid builders below — neither has a `schoolYearId` filter of its own that
 * would let it skip this the way `dateRange`'s callers do.
 */
async function activeSchoolYear(
  schoolId: string
): Promise<{ startDate: Date; endDate: Date; label: string } | null> {
  return prisma.schoolYear.findFirst({
    where: { schoolId, isActive: true },
    select: { startDate: true, endDate: true, label: true },
  });
}

/** The school year LABEL only, honoring `filters.schoolYearId` when set —
 * used by builders (Term Grades, MOSY-adjacent) that do not already read the
 * active school year for range math the way the two grid builders do. */
async function schoolYearLabelFor(
  schoolId: string,
  schoolYearId?: string | null
): Promise<string | null> {
  const year = await prisma.schoolYear.findFirst({
    where: { schoolId, ...(schoolYearId ? { id: schoolYearId } : { isActive: true }) },
    select: { label: true },
  });
  return year?.label ?? null;
}

/**
 * The DepEd-style header block ("School ID", "School Name", ...) drawn at
 * the top of every sheet/page (`render.ts`). One tenancy-safe read, pinned to
 * `scope.schoolId` — the only place any report builder reads School fields
 * beyond the name already carried on `scope`.
 */
async function buildReportHeader(
  scope: ReportScope,
  extra: { schoolYearLabel?: string | null; gradeSectionLabel?: string | null } = {}
): Promise<ReportHeaderField[]> {
  const school = await prisma.school.findFirst({
    where: { id: scope.schoolId, deletedAt: null },
    select: { schoolIdCode: true, name: true, region: true, division: true, district: true },
  });
  const fields: ReportHeaderField[] = [
    { label: "School ID", value: school?.schoolIdCode ?? "—" },
    { label: "School Name", value: school?.name ?? scope.schoolName },
  ];
  if (school?.region) fields.push({ label: "Region", value: school.region });
  if (school?.division) fields.push({ label: "Division", value: school.division });
  if (school?.district) fields.push({ label: "District", value: school.district });
  fields.push(
    { label: "School Year", value: extra.schoolYearLabel ?? "—" },
    { label: "Grade / Section", value: extra.gradeSectionLabel ?? "All" },
    { label: "Prepared by", value: scope.actorName }
  );
  return fields;
}

/** "Grade 3 - A" from the first learner in an already-filtered roster, else "All Classes" / a grade-only label. */
function gradeSectionLabelFromLearners(
  learners: { gradeLevel: { type: string }; section: { name: string } | null }[],
  filters: ReportFilters
): string {
  const first = learners[0];
  if (filters.sectionId && first) {
    return `${GRADE_LEVEL_LABELS[first.gradeLevel.type] ?? first.gradeLevel.type} - ${first.section?.name ?? "—"}`;
  }
  if (filters.gradeLevelId && first) {
    return GRADE_LEVEL_LABELS[first.gradeLevel.type] ?? first.gradeLevel.type;
  }
  return "All Classes";
}

/**
 * Attendance and Weekly Reading Level render a GRID: every date/period in the
 * resolved range crossed with every in-scope learner, blank where nothing was
 * recorded yet, so a teacher sees the gaps rather than a report that only
 * shows what already got entered. The two builders below share the range
 * resolution and cap logic (`./grid.ts`); only the axis (day vs. month) and
 * the record shape differ.
 */
export async function buildAttendanceTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTable> {
  // The school year is only needed to resolve a default/partial range; a
  // caller-supplied `from` never depends on it (see `resolveDateRange`).
  const schoolYear = filters.from ? null : await activeSchoolYear(scope.schoolId);
  const range = resolveDateRange(filters, schoolYear, schoolToday());

  const [learners, records] = await Promise.all([
    prisma.learner.findMany({
      where: learnerWhere(scope, filters),
      select: {
        id: true,
        firstName: true,
        middleName: true,
        lastName: true,
        gender: true,
        gradeLevel: { select: { type: true } },
        section: { select: { name: true } },
      },
      orderBy: [{ lastName: "asc" }, { firstName: "asc" }, { id: "asc" }],
      // Bounded like every other bulk read here: a school with more learners
      // than this is far more rows than a report is useful at.
      take: 5000,
    }),
    prisma.attendance.findMany({
      where: {
        date: dateRange({ from: range.startKey, to: range.endKey }),
        learner: learnerWhere(scope, filters),
      },
      select: { date: true, status: true, notes: true, learnerId: true },
      orderBy: [{ date: "asc" }],
      take: 20000,
    }),
  ]);

  const recordDateKeys = [...new Set(records.map((r) => formatLocalDateKey(r.date)))];
  const weekdays = enumerateWeekdays(range.startKey, range.endKey);
  const allDates = unionDateKeys(weekdays, recordDateKeys);
  const { keys: dates, capped } = capGridKeys(allDates, learners.length);

  const byCell = new Map<string, (typeof records)[number]>();
  for (const r of records) {
    byCell.set(`${r.learnerId}|${formatLocalDateKey(r.date)}`, r);
  }

  const rows: (string | number | null)[][] = [];
  for (const dateKey of dates) {
    for (const learner of learners) {
      const r = byCell.get(`${learner.id}|${dateKey}`);
      rows.push([
        dateKey,
        formatListingNameFromRecord(learner),
        GRADE_LEVEL_LABELS[learner.gradeLevel.type] ?? learner.gradeLevel.type,
        learner.section?.name ?? "—",
        r ? (ATTENDANCE_STATUS_LABELS[r.status] ?? r.status) : "",
        r ? (r.notes ?? "") : "",
      ]);
    }
  }

  // SF2-style blocks (`renderExcel`/`renderPdf` read `blocks`, not the flat
  // `columns`/`rows` above — see `reportBlocks`). The flat shape above is kept
  // byte-for-byte: `generateReport`'s audit metadata (`table.rows.length`)
  // and every existing test still read it.
  const includeGradeSection = !filters.sectionId;
  const sf2Learners: Sf2Learner[] = learners.map((l) => ({
    id: l.id,
    displayName: formatListingNameFromRecord(l),
    sex: l.gender === "MALE" || l.gender === "FEMALE" ? l.gender : null,
    gradeLabel: GRADE_LEVEL_LABELS[l.gradeLevel.type] ?? l.gradeLevel.type,
    sectionLabel: l.section?.name ?? "—",
  }));
  const cellFor = (learnerId: string, dayKey: string): Sf2Status | null => {
    const r = byCell.get(`${learnerId}|${dayKey}`);
    return r ? (r.status as Sf2Status) : null;
  };
  const blocks = buildSf2Blocks({
    learners: sf2Learners,
    dayKeys: dates,
    cellFor,
    includeGradeSection,
  });

  const header = await buildReportHeader(scope, {
    schoolYearLabel: schoolYear?.label ?? null,
    gradeSectionLabel: gradeSectionLabelFromLearners(learners, filters),
  });

  return {
    title: "Attendance Records",
    subtitle: subtitleForGrid(scope, [
      range.label,
      `${learners.length} learner(s), ${dates.length} school day(s), ${records.length} record(s)`,
      ...(capped ? [capNote(dates.length, "school day")] : []),
    ]),
    columns: [
      { header: "Date", width: 12 },
      { header: "Learner", width: 28 },
      { header: "Grade", width: 12 },
      { header: "Section", width: 14 },
      { header: "Status", width: 12 },
      { header: "Reason / Remarks", width: 30 },
    ],
    rows,
    blocks,
    header,
  };
}

/**
 * `ReadingLevelRecord.weekStart` names a MONTH's assessment (the live monthly
 * writer stores the 1st of the month) except on rows the retired weekly grid
 * left behind, which hold a Monday. Periods are therefore the 1st of every
 * month in range UNION every record's `weekStart` actually seen — never just
 * one or the other, or a legacy Monday row would either vanish or the grid
 * would gain a stray non-1st column no month owns.
 */
export async function buildReadingLevelTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTable> {
  const schoolYear = filters.from ? null : await activeSchoolYear(scope.schoolId);
  const range = resolveDateRange(filters, schoolYear, schoolToday());

  const [learners, records] = await Promise.all([
    prisma.learner.findMany({
      where: learnerWhere(scope, filters),
      select: {
        id: true,
        firstName: true,
        middleName: true,
        lastName: true,
        gender: true,
        gradeLevel: { select: { type: true } },
        section: { select: { name: true } },
      },
      orderBy: [{ lastName: "asc" }, { firstName: "asc" }, { id: "asc" }],
      take: 5000,
    }),
    prisma.readingLevelRecord.findMany({
      where: {
        weekStart: dateRange({ from: range.startKey, to: range.endKey }),
        learner: learnerWhere(scope, filters),
      },
      select: {
        weekStart: true,
        englishProfile: true,
        filipinoProfile: true,
        wordRecognitionLevel: true,
        readingComprehensionLevel: true,
        writingLevel: true,
        notes: true,
        learnerId: true,
      },
      orderBy: [{ weekStart: "asc" }],
      take: 20000,
    }),
  ]);

  const recordPeriodKeys = [...new Set(records.map((r) => formatLocalDateKey(r.weekStart)))];
  const monthStarts = enumerateMonthStarts(range.startKey, range.endKey);
  const allPeriods = unionDateKeys(monthStarts, recordPeriodKeys);
  const { keys: periods, capped } = capGridKeys(allPeriods, learners.length);

  const byCell = new Map<string, (typeof records)[number]>();
  for (const r of records) {
    byCell.set(`${r.learnerId}|${formatLocalDateKey(r.weekStart)}`, r);
  }

  const rows: (string | number | null)[][] = [];
  for (const periodKey of periods) {
    for (const learner of learners) {
      const r = byCell.get(`${learner.id}|${periodKey}`);
      rows.push([
        periodKey,
        formatListingNameFromRecord(learner),
        GRADE_LEVEL_LABELS[learner.gradeLevel.type] ?? learner.gradeLevel.type,
        learner.section?.name ?? "—",
        r?.englishProfile ? (READING_PROFILE_LABELS[r.englishProfile] ?? r.englishProfile) : "",
        r?.filipinoProfile ? (READING_PROFILE_LABELS[r.filipinoProfile] ?? r.filipinoProfile) : "",
        r?.wordRecognitionLevel
          ? (WEEKLY_WORD_RECOGNITION_LEVEL_LABELS[r.wordRecognitionLevel] ??
            r.wordRecognitionLevel)
          : "",
        r?.readingComprehensionLevel
          ? (WEEKLY_READING_COMPREHENSION_LEVEL_LABELS[r.readingComprehensionLevel] ??
            r.readingComprehensionLevel)
          : "",
        r?.writingLevel ? (WEEKLY_WRITING_LEVEL_LABELS[r.writingLevel] ?? r.writingLevel) : "",
        r ? (r.notes ?? "") : "",
      ]);
    }
  }

  // Sex-grouped, blank-filled roster per period, one Excel sheet per period —
  // `renderExcel`/`renderPdf` read `blocks` over the flat `rows` above once
  // it is set (`reportBlocks`); the flat shape is kept exactly as before for
  // every existing reader (audit metadata, existing tests).
  const includeGradeSection = !filters.sectionId;
  const sf2Learners: Sf2Learner[] = learners.map((l) => ({
    id: l.id,
    displayName: formatListingNameFromRecord(l),
    sex: l.gender === "MALE" || l.gender === "FEMALE" ? l.gender : null,
    gradeLabel: GRADE_LEVEL_LABELS[l.gradeLevel.type] ?? l.gradeLevel.type,
    sectionLabel: l.section?.name ?? "—",
  }));
  const blocks: NonNullable<ReportTable["blocks"]> = periods.map((periodKey) => {
    const columns = [
      { header: "#", width: 5 },
      { header: "Learner", width: 26 },
      ...(includeGradeSection
        ? [{ header: "Grade", width: 11 }, { header: "Section", width: 12 }]
        : []),
      { header: "English", width: 22 },
      { header: "Filipino", width: 22 },
      { header: "Word Recognition", width: 18 },
      { header: "Comprehension", width: 18 },
      { header: "Writing", width: 16 },
      { header: "Remarks", width: 24 },
    ];
    const blockRows: (string | number | null)[][] = [];
    const boldRowIndices: number[] = [];
    let seq = 0;
    for (const { sex, group } of groupBySex(sf2Learners)) {
      if (group.length === 0) continue;
      boldRowIndices.push(blockRows.length);
      blockRows.push([sex ?? "NOT SPECIFIED", ...new Array(columns.length - 1).fill(null)]);
      for (const sf2Learner of group) {
        const r = byCell.get(`${sf2Learner.id}|${periodKey}`);
        seq += 1;
        blockRows.push([
          seq,
          sf2Learner.displayName,
          ...(includeGradeSection ? [sf2Learner.gradeLabel, sf2Learner.sectionLabel] : []),
          r?.englishProfile ? (READING_PROFILE_LABELS[r.englishProfile] ?? r.englishProfile) : "",
          r?.filipinoProfile ? (READING_PROFILE_LABELS[r.filipinoProfile] ?? r.filipinoProfile) : "",
          r?.wordRecognitionLevel
            ? (WEEKLY_WORD_RECOGNITION_LEVEL_LABELS[r.wordRecognitionLevel] ?? r.wordRecognitionLevel)
            : "",
          r?.readingComprehensionLevel
            ? (WEEKLY_READING_COMPREHENSION_LEVEL_LABELS[r.readingComprehensionLevel] ??
              r.readingComprehensionLevel)
            : "",
          r?.writingLevel ? (WEEKLY_WRITING_LEVEL_LABELS[r.writingLevel] ?? r.writingLevel) : "",
          r ? (r.notes ?? "") : "",
        ]);
      }
    }
    return {
      heading: `Weekly Reading Level — ${periodKey}`,
      sheetName: periodKey,
      columns,
      rows: blockRows,
      boldRowIndices,
      freezeColumns: includeGradeSection ? 4 : 2,
    };
  });

  const header = await buildReportHeader(scope, {
    schoolYearLabel: schoolYear?.label ?? null,
    gradeSectionLabel: gradeSectionLabelFromLearners(learners, filters),
  });

  return {
    title: "Weekly Reading Level",
    subtitle: subtitleForGrid(scope, [
      range.label,
      `${learners.length} learner(s), ${periods.length} period(s), ${records.length} assessment(s)`,
      ...(capped ? [capNote(periods.length, "period")] : []),
    ]),
    columns: [
      { header: "Period", width: 12 },
      { header: "Learner", width: 26 },
      { header: "Grade", width: 11 },
      { header: "Section", width: 12 },
      { header: "English", width: 22 },
      { header: "Filipino", width: 22 },
      { header: "Word Recognition", width: 18 },
      { header: "Comprehension", width: 18 },
      { header: "Writing", width: 16 },
      { header: "Remarks", width: 24 },
    ],
    rows,
    blocks,
    header,
  };
}

/** Grade types with no numeric/lettered End of Terms sheet at all. */
const NO_TERM_SHEET_GRADE_TYPES = new Set(["KINDER", "FLOATING"]);

export async function buildTermGradesTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTable> {
  const terms = (
    filters.term ? [filters.term as "FIRST" | "SECOND" | "THIRD"] : (["FIRST", "SECOND", "THIRD"] as const)
  );

  const learners = await prisma.learner.findMany({
    where: learnerWhere(scope, filters),
    select: {
      id: true,
      firstName: true,
      middleName: true,
      lastName: true,
      gradeLevelId: true,
      gradeLevel: { select: { type: true } },
      section: { select: { name: true } },
    },
    orderBy: [{ lastName: "asc" }, { firstName: "asc" }, { id: "asc" }],
    take: 5000,
  });
  const gradeLevelIds = [...new Set(learners.map((l) => l.gradeLevelId))];

  const [rows, sheetSubjects] = await Promise.all([
    prisma.termGrade.findMany({
      where: {
        ...(filters.schoolYearId ? { schoolYearId: filters.schoolYearId } : {}),
        ...(filters.term
          ? { term: filters.term as "FIRST" | "SECOND" | "THIRD" }
          : {}),
        learner: learnerWhere(scope, filters),
        // Archived subjects are hidden everywhere, reports included. The subject
        // row's own school is pinned too, on top of the learner's.
        termSubject: { schoolId: scope.schoolId, deletedAt: null },
      },
      select: {
        term: true,
        score: true,
        mark: true,
        updatedAt: true,
        termSubject: { select: { name: true, position: true, gradeLevelId: true } },
        learner: {
          select: {
            id: true,
            firstName: true,
            middleName: true,
            lastName: true,
            gradeLevelId: true,
            gradeLevel: { select: { type: true } },
            section: { select: { name: true } },
          },
        },
      },
      orderBy: [
        { learner: { lastName: "asc" } },
        { learner: { firstName: "asc" } },
        { id: "asc" },
      ],
      take: 10000,
    }),
    // The sheet's subjects for every grade an in-scope learner currently sits
    // in — this is what makes a term with zero recorded grades still show
    // every column the sheet defines, not just the ones somebody has typed
    // into so far.
    gradeLevelIds.length > 0
      ? prisma.termSubject.findMany({
          where: { schoolId: scope.schoolId, deletedAt: null, gradeLevelId: { in: gradeLevelIds } },
          select: { name: true, position: true },
        })
      : Promise.resolve([]),
  ]);

  // One row per learner per term, subjects across — the shape the DepEd sheet
  // is read in. A flat row-per-grade dump is unusable at a parent conference.
  //
  // Grades may name their subjects differently, so columns group by name key
  // (trim + lowercase) across grades, ordered by the lowest position any grade
  // gives that name, then by name. The header is the first spelling seen —
  // the sheet subjects are read before any recorded-grade subject, so a
  // subject that is on the sheet keeps the sheet's own spelling even if a
  // stale recorded row differs only in case.
  const columnByKey = new Map<string, { header: string; position: number }>();
  const addSubjectColumn = (name: string, position: number) => {
    const key = subjectNameKey(name);
    const existing = columnByKey.get(key);
    if (!existing) {
      columnByKey.set(key, { header: name.trim(), position });
    } else if (position < existing.position) {
      existing.position = position;
    }
  };
  for (const s of sheetSubjects) addSubjectColumn(s.name, s.position);
  for (const r of rows) {
    if (r.termSubject) addSubjectColumn(r.termSubject.name, r.termSubject.position);
  }
  const subjects = [...columnByKey.entries()]
    .sort(
      ([ka, a], [kb, b]) =>
        a.position - b.position || (ka < kb ? -1 : ka > kb ? 1 : 0)
    )
    .map(([key]) => key);
  type Group = {
    name: string;
    grade: string;
    section: string;
    term: string;
    /** Raw `GradeLevelType` of the learner's current grade: picks the scale. */
    gradeType: string;
    scores: Map<string, TermCell>;
    picks: Map<string, { cell: TermCell; current: boolean; updatedAt: number }>;
  };
  const groups = new Map<string, Group>();

  // Blank-fill: every in-scope learner whose grade carries a term sheet gets
  // one row per term in scope, even with zero `TermGrade` rows. A learner in
  // KINDER or FLOATING has no numeric sheet at all, so they are seeded with
  // nothing here — the loop below still gives them a row if they somehow hold
  // a recorded grade (a moved-grade leftover), matching the "recorded rows
  // only" rule.
  for (const l of learners) {
    const gradeType = l.gradeLevel.type;
    if (NO_TERM_SHEET_GRADE_TYPES.has(gradeType)) continue;
    for (const term of terms) {
      groups.set(`${l.id}:${term}`, {
        name: formatListingNameFromRecord(l),
        grade: GRADE_LEVEL_LABELS[gradeType] ?? gradeType,
        section: l.section?.name ?? "—",
        term: TERM_PERIOD_LABELS[term] ?? term,
        gradeType,
        scores: new Map(),
        picks: new Map(),
      });
    }
  }

  for (const r of rows) {
    const key = `${r.learner.id}:${r.term}`;
    let g = groups.get(key);
    if (!g) {
      g = {
        name: formatListingNameFromRecord(r.learner),
        grade:
          GRADE_LEVEL_LABELS[r.learner.gradeLevel.type] ?? r.learner.gradeLevel.type,
        section: r.learner.section?.name ?? "—",
        term: TERM_PERIOD_LABELS[r.term] ?? r.term,
        gradeType: r.learner.gradeLevel.type,
        scores: new Map(),
        picks: new Map(),
      };
      groups.set(key, g);
    }
    if (!r.termSubject) continue;
    // A learner who moved grades can hold two scores under one name key (e.g.
    // "English" in both grades). Deterministic pick: the current grade's
    // subject wins; otherwise the most recently updated row; ties keep the
    // first seen.
    const nameKey = subjectNameKey(r.termSubject.name);
    const candidate = {
      cell: { score: r.score, mark: r.mark ?? null },
      current: r.termSubject.gradeLevelId === r.learner.gradeLevelId,
      updatedAt: r.updatedAt.getTime(),
    };
    const held = g.picks.get(nameKey);
    if (
      !held ||
      (candidate.current && !held.current) ||
      (candidate.current === held.current && candidate.updatedAt > held.updatedAt)
    ) {
      g.picks.set(nameKey, candidate);
      g.scores.set(nameKey, candidate.cell);
    }
  }

  const header = await buildReportHeader(scope, {
    schoolYearLabel: await schoolYearLabelFor(scope.schoolId, filters.schoolYearId),
    gradeSectionLabel: gradeSectionLabelFromLearners(learners, filters),
  });

  return {
    title: "End of Term Report (Grades)",
    subtitle: subtitleFor(scope, filters, [`${groups.size} learner-term row(s)`]),
    header,
    columns: [
      { header: "Learner", width: 26 },
      { header: "Grade", width: 11 },
      { header: "Section", width: 12 },
      { header: "Term", width: 12 },
      ...subjects.map((s) => ({
        header: columnByKey.get(s)?.header ?? s,
        width: 12,
      })),
      { header: "General Average", width: 14 },
    ],
    rows: [...groups.values()].map((g) => {
      const cells = subjects.map((s) => g.scores.get(s) ?? null);
      // A score stays a number cell, exactly as before; a mark is its full
      // label ("A – Advancing").
      const values = cells.map((c) =>
        !c ? null : c.mark ? termCellText(c) : c.score
      );
      // Null for Grade 1 (letter marks) and for any row holding a mark. Whole
      // number, as this report has always shown it.
      const mean = rowGeneralAverage(g.gradeType, cells);
      const average = mean === null ? null : Math.round(mean);
      return [g.name, g.grade, g.section, g.term, ...values, average];
    }),
  };
}

export async function buildClassRosterTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTable> {
  const learners = await prisma.learner.findMany({
    where: learnerWhere(scope, filters),
    select: {
      id: true,
      firstName: true,
      middleName: true,
      lastName: true,
      gender: true,
      isAralLearner: true,
      gradeLevel: { select: { type: true } },
      section: { select: { name: true } },
    },
    orderBy: [{ lastName: "asc" }, { firstName: "asc" }, { id: "asc" }],
    take: 5000,
  });

  return {
    title: "Class Roster",
    subtitle: subtitleFor(scope, filters, [`${learners.length} learner(s)`]),
    columns: [
      { header: "#", width: 6 },
      { header: "Learner", width: 30 },
      { header: "Grade", width: 14 },
      { header: "Section", width: 16 },
      { header: "Gender", width: 10 },
      { header: "ARAL", width: 8 },
    ],
    rows: learners.map((l, i) => [
      i + 1,
      formatListingNameFromRecord(l),
      GRADE_LEVEL_LABELS[l.gradeLevel.type] ?? l.gradeLevel.type,
      l.section?.name ?? "—",
      l.gender ?? "",
      l.isAralLearner ? "Yes" : "No",
    ]),
  };
}

/**
 * One row per class, aggregating what the three record reports show per learner:
 * headcount, attendance rate, and how many learners are reading at grade level.
 */
export async function buildTeacherSummaryTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTable> {
  const range = dateRange(filters);

  const sections = await prisma.section.findMany({
    where: {
      schoolId: scope.schoolId,
      deletedAt: null,
      ...(filters.sectionId ? { id: filters.sectionId } : {}),
      gradeLevel: {
        ...gradeWhere(scope),
        ...(filters.gradeLevelId ? { id: filters.gradeLevelId } : {}),
      },
    },
    select: {
      id: true,
      name: true,
      gradeLevel: { select: { type: true } },
      adviser: { select: { firstName: true, middleName: true, lastName: true } },
    },
    orderBy: { name: "asc" },
    take: 200,
  });

  const rows: (string | number | null)[][] = [];

  for (const section of sections) {
    const scopedLearners = {
      ...learnerWhere(scope, { ...filters, sectionId: section.id }),
    };

    const [learnerCount, aralCount, attendance, gradeReady] = await Promise.all([
      prisma.learner.count({ where: scopedLearners }),
      prisma.learner.count({ where: { ...scopedLearners, isAralLearner: true } }),
      prisma.attendance.groupBy({
        by: ["status"],
        where: {
          ...(range ? { date: range } : {}),
          learner: scopedLearners,
        },
        _count: { _all: true },
      }),
      prisma.readingLevelRecord.count({
        where: {
          ...(range ? { weekStart: range } : {}),
          learner: scopedLearners,
          englishProfile: "INDEPENDENT_GRADE_READY",
        },
      }),
    ]);

    const counts = new Map(attendance.map((a) => [a.status, a._count._all]));
    const present = (counts.get("PRESENT") ?? 0) + (counts.get("LATE") ?? 0);
    const absent = counts.get("ABSENT") ?? 0;
    const excused = counts.get("EXCUSED") ?? 0;
    const marked = present + absent + excused;
    // Guarded, not `|| 0`: a class with no marked days must read "—" rather
    // than 0%, which would be indistinguishable from perfect absenteeism.
    const rate = marked > 0 ? `${Math.round((present / marked) * 100)}%` : "—";

    rows.push([
      `${GRADE_LEVEL_LABELS[section.gradeLevel.type] ?? section.gradeLevel.type} - ${section.name}`,
      section.adviser ? formatListingNameFromRecord(section.adviser) : "—",
      learnerCount,
      aralCount,
      present,
      absent,
      excused,
      rate,
      gradeReady,
    ]);
  }

  return {
    title: "Teacher Summary",
    subtitle: subtitleFor(scope, filters, [`${sections.length} class(es)`]),
    columns: [
      { header: "Class", width: 22 },
      { header: "Adviser", width: 24 },
      { header: "Learners", width: 10 },
      { header: "ARAL", width: 8 },
      { header: "Present", width: 10 },
      { header: "Absent", width: 10 },
      { header: "Excused", width: 10 },
      { header: "Attendance Rate", width: 14 },
      { header: "Grade-level Readers", width: 16 },
    ],
    rows,
  };
}

/**
 * MOSY ("Middle of School Year") — the school year's SECOND TERM window.
 *
 * Three reads, no per-grade fan-out: the school year (plus its term-window
 * overrides), the grades in scope, and the learners in scope with their
 * in-window reading records attached. `buildMosyBlocks` (`./mosy.ts`) turns
 * the result into the four blocks; every decision about bands, percentages
 * and ARAL counts lives there, so this function only fetches and shapes.
 *
 * TENANCY. The school-year and override reads are the only `where`s in this
 * file that are not already `learnerWhere`/`gradeWhere`, so both pin
 * `schoolId` explicitly. The override table denormalises `schoolId` for
 * exactly this reason (`prisma/schema.prisma` § TermWindowOverride).
 *
 * The report ALWAYS generates. No school year, no override, no ARAL profile
 * and no reading record are all ordinary states — an unresolved window simply
 * means every learner reads as not assessed (see `docs/aral-profile.md` for
 * the standing rule that nothing may gate on `AralProfile`).
 */
export async function buildMosyTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTableWithAudit> {
  const schoolYear = await prisma.schoolYear.findFirst({
    where: {
      schoolId: scope.schoolId,
      ...(filters.schoolYearId ? { id: filters.schoolYearId } : { isActive: true }),
    },
    select: { id: true, startDate: true, endDate: true, label: true },
  });

  const overrides = schoolYear
    ? await prisma.termWindowOverride.findMany({
        where: { schoolId: scope.schoolId, schoolYearId: schoolYear.id },
        select: { term: true, startKey: true, endKey: true, deadlineKey: true },
      })
    : [];

  const window = resolveMosyWindowInfo(schoolYear, overrides, filters);

  // A supplied edge replaces the MOSY edge; the unsupplied one keeps its MOSY
  // value. Routed back through `dateRange` rather than re-derived, so the
  // half-open `lt: to + 1 day` rule has one answer for every report here.
  const range =
    window.startKey || window.endKey
      ? dateRange({ ...filters, from: window.startKey, to: window.endKey })
      : undefined;
  // Unresolved window: match no record at all. Omitting the filter instead
  // would silently widen the report to a learner's whole history and still
  // label it MOSY, which is worse than showing everyone as not assessed.
  const recordWhere: Prisma.ReadingLevelRecordWhereInput = range
    ? { weekStart: range }
    : { id: { in: [] } };

  const [grades, learners] = await Promise.all([
    prisma.gradeLevel.findMany({
      where: {
        ...gradeWhere(scope),
        ...(filters.gradeLevelId ? { id: filters.gradeLevelId } : {}),
      },
      select: { id: true, type: true },
      orderBy: { type: "asc" },
    }),
    prisma.learner.findMany({
      where: learnerWhere(scope, filters),
      select: {
        id: true,
        firstName: true,
        middleName: true,
        lastName: true,
        gender: true,
        gradeLevelId: true,
        isAralLearner: true,
        gradeLevel: { select: { type: true } },
        section: { select: { name: true } },
        aralTeacher: { select: { firstName: true, middleName: true, lastName: true } },
        // A `select`, never a `where`: gating the learner read on a profile
        // would empty this report for every school that has filled none in.
        aralProfile: { select: { updatedAt: true, suggestedInterventions: true } },
        readingLevels: {
          where: recordWhere,
          select: {
            weekStart: true,
            englishProfile: true,
            filipinoProfile: true,
            wordRecognitionLevel: true,
            readingComprehensionLevel: true,
          },
          orderBy: { weekStart: "desc" },
        },
      },
      orderBy: [{ lastName: "asc" }, { firstName: "asc" }, { id: "asc" }],
      // Bounded like every other bulk read in this file.
      take: 5000,
    }),
  ]);

  const mosyLearners: MosyLearner[] = learners.map((learner) => {
    const gradeType = learner.gradeLevel.type;
    return {
      id: learner.id,
      gradeLevelId: learner.gradeLevelId,
      gradeType,
      gradeLabel: GRADE_LEVEL_LABELS[gradeType] ?? gradeType,
      sectionName: learner.section?.name ?? null,
      firstName: learner.firstName,
      middleName: learner.middleName,
      lastName: learner.lastName,
      sex: learner.gender === "MALE" || learner.gender === "FEMALE" ? learner.gender : null,
      isAralLearner: learner.isAralLearner,
      // Scope is advised UNION ARAL-tutored (`teacherLearnerScope`), as in
      // every other builder, so the tutor's name is what makes visible which
      // learners are here on the ARAL axis rather than the advisory one.
      aralTutorName: learner.aralTeacher
        ? formatListingNameFromRecord(learner.aralTeacher)
        : null,
      record: pickMosyRecord(learner.readingLevels, gradeType),
      profile: learner.aralProfile
        ? {
            updatedAtKey: formatLocalDateKey(learner.aralProfile.updatedAt),
            interventions: learner.aralProfile.suggestedInterventions,
          }
        : null,
    };
  });

  const blocks = buildMosyBlocks({
    window,
    grades: grades.map((g) => ({
      id: g.id,
      type: g.type,
      label: GRADE_LEVEL_LABELS[g.type] ?? g.type,
    })),
    learners: mosyLearners,
  });

  const windowNote = describeMosyWindowNote(window);
  const assessed = mosyLearners.filter((l) => l.record !== null).length;
  const detail = blocks[blocks.length - 1];

  const header = await buildReportHeader(scope, {
    schoolYearLabel: schoolYear?.label ?? null,
    gradeSectionLabel: gradeSectionLabelFromLearners(learners, filters),
  });

  return {
    title: "MOSY Report",
    subtitle: subtitleFor(scope, filters, [
      schoolYear
        ? `School Year: ${schoolYear.label} (${formatLocalDateKey(schoolYear.startDate)} to ${formatLocalDateKey(schoolYear.endDate)})`
        : "School Year: none resolved",
      `MOSY window: ${window.label}`,
      `${mosyLearners.length} learner(s), ${assessed} assessed in window`,
      ...(windowNote ? [windowNote] : []),
    ]),
    header,
    // `blocks` is what both renderers read (`reportBlocks`). The learner
    // detail block is mirrored into the flat pair so anything still reading
    // `columns`/`rows` sees the row-per-learner listing rather than nothing.
    columns: detail.columns,
    rows: detail.rows,
    blocks,
    auditMeta: {
      windowStartKey: window.startKey,
      windowEndKey: window.endKey,
      windowSource: window.source,
      grades: grades.length,
      learners: mosyLearners.length,
      assessedLearners: assessed,
    },
  };
}

/**
 * The MOSY window: the school year's Second Term, with each supplied filter
 * edge REPLACING the corresponding MOSY edge while the unsupplied edge keeps
 * its MOSY value. No school year and no supplied edge is `"unresolved"` — a
 * state the report renders, never an error.
 */
function resolveMosyWindowInfo(
  schoolYear: { startDate: Date } | null,
  overrides: { term: string; startKey: string; endKey: string; deadlineKey: string }[],
  filters: ReportFilters
): MosyWindowInfo {
  const mosy = schoolYear
    ? resolveMosyWindow(
        schoolYear.startDate,
        overrides.map((o) => ({
          term: o.term as TermPeriodValue,
          startKey: o.startKey,
          endKey: o.endKey,
          deadlineKey: o.deadlineKey,
        }))
      )
    : null;

  const startKey = filters.from ?? mosy?.startKey ?? null;
  const endKey = filters.to ?? mosy?.endKey ?? null;

  if (!startKey && !endKey) {
    return { startKey: null, endKey: null, label: "Unresolved", source: "unresolved" };
  }
  if (filters.from || filters.to) {
    return {
      startKey,
      endKey,
      label: `${startKey ?? "start"} to ${endKey ?? "today"}`,
      source: "custom",
    };
  }
  return { startKey, endKey, label: mosy?.label ?? "Unresolved", source: "term" };
}

/**
 * The record a learner is judged on: among their in-window records, the one
 * with the greatest `weekStart` that is COMPLETE for their grade; if none is
 * complete, the greatest `weekStart`, marked not-complete.
 *
 * Deterministic without a tiebreaker because `@@unique([learnerId,
 * weekStart])` makes two records on one day impossible, and the caller reads
 * them already ordered `weekStart` desc.
 */
function pickMosyRecord(
  records: {
    weekStart: Date;
    englishProfile: string | null;
    filipinoProfile: string | null;
    wordRecognitionLevel: string | null;
    readingComprehensionLevel: string | null;
  }[],
  gradeType: string
): MosyLearner["record"] {
  const complete = records.find((r) => isReadingRecordComplete(r, gradeType));
  const chosen = complete ?? records[0];
  if (!chosen) return null;
  return {
    weekStartKey: formatLocalDateKey(chosen.weekStart),
    englishProfile: chosen.englishProfile,
    filipinoProfile: chosen.filipinoProfile,
    wordRecognitionLevel: chosen.wordRecognitionLevel,
    readingComprehensionLevel: chosen.readingComprehensionLevel,
    complete: complete !== undefined,
  };
}
