import "server-only";

import type { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { teacherGradeScope, teacherLearnerScope } from "@/lib/teachers/scope";
import {
  ATTENDANCE_STATUS_LABELS,
  GRADE_LEVEL_LABELS,
  LEARNING_AREA_LABELS,
  READING_PROFILE_LABELS,
  TERM_PERIOD_LABELS,
  WEEKLY_READING_COMPREHENSION_LEVEL_LABELS,
  WEEKLY_WORD_RECOGNITION_LEVEL_LABELS,
  WEEKLY_WRITING_LEVEL_LABELS,
} from "@/lib/constants/enum-labels";
import { formatLocalDateKey, parseLocalDateKey } from "@/lib/date-keys";
import type { ReportFilters } from "@/lib/reports/kinds";
import type { ReportTable } from "@/lib/reports/render";

/**
 * The data half of the Reports Hub: one builder per report kind, each returning
 * the same `ReportTable` so `render.ts` can emit Excel or PDF without knowing
 * what it is looking at.
 *
 * TENANCY. Every builder receives an already-resolved `scope` and must spread
 * its `learnerWhere` / `gradeWhere` into its own `where`. The scope is built
 * once, in `reportScope()` below, from the signed-in user — a builder never
 * reads the session itself, so there is exactly one place a tenant predicate
 * could go missing rather than five.
 */

export type ReportScope = {
  schoolId: string;
  /** Set only for a real TEACHER; a Super Admin viewing a school is not one. */
  teacherId: string | null;
  schoolName: string;
  actorName: string;
};

export function reportScope(args: ReportScope): ReportScope {
  return args;
}

/** Learner rows this actor may see at all, before the hub's own filters. */
function learnerWhere(
  scope: ReportScope,
  filters: ReportFilters
): Prisma.LearnerWhereInput {
  return {
    schoolId: scope.schoolId,
    deletedAt: null,
    archivedAt: null,
    ...(scope.teacherId ? teacherLearnerScope(scope.teacherId) : {}),
    ...(filters.gradeLevelId ? { gradeLevelId: filters.gradeLevelId } : {}),
    ...(filters.sectionId ? { sectionId: filters.sectionId } : {}),
  };
}

/** Grade rows this actor may see, used by the summary report. */
function gradeWhere(scope: ReportScope): Prisma.GradeLevelWhereInput {
  return {
    schoolId: scope.schoolId,
    deletedAt: null,
    ...(scope.teacherId ? teacherGradeScope(scope.teacherId) : {}),
  };
}

/**
 * `from`/`to` as an inclusive day range on a `@db.Date` column.
 *
 * `to` becomes `lt: to + 1 day` rather than `lte: to`: a `@db.Date` column
 * compares against local midnight, so `lte` would still include the whole of
 * `to` here but breaks the moment the column becomes a timestamp. Written as a
 * half-open range it is correct either way.
 */
function dateRange(filters: ReportFilters): { gte?: Date; lt?: Date } | undefined {
  const range: { gte?: Date; lt?: Date } = {};
  if (filters.from) range.gte = parseLocalDateKey(filters.from);
  if (filters.to) {
    const to = parseLocalDateKey(filters.to);
    range.lt = new Date(to.getFullYear(), to.getMonth(), to.getDate() + 1);
  }
  return range.gte || range.lt ? range : undefined;
}

function subtitleFor(
  scope: ReportScope,
  filters: ReportFilters,
  extra: string[] = []
): string[] {
  const parts: string[] = [scope.schoolName];
  if (filters.from || filters.to) {
    parts.push(`Range: ${filters.from ?? "start"} to ${filters.to ?? "today"}`);
  }
  return [
    ...parts,
    ...extra,
    `Generated by ${scope.actorName} on ${formatLocalDateKey(new Date())}`,
  ];
}

export async function buildAttendanceTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTable> {
  const range = dateRange(filters);
  const rows = await prisma.attendance.findMany({
    where: {
      ...(range ? { date: range } : {}),
      learner: learnerWhere(scope, filters),
    },
    select: {
      date: true,
      status: true,
      notes: true,
      learner: {
        select: {
          fullName: true,
          gradeLevel: { select: { type: true } },
          section: { select: { name: true } },
        },
      },
    },
    orderBy: [{ date: "asc" }, { learner: { fullName: "asc" } }],
    // Bounded like every other bulk read here: a year of a large school is far
    // more rows than a report is useful at, and an unbounded findMany is how a
    // lambda runs out of memory.
    take: 5000,
  });

  return {
    title: "Attendance Records",
    subtitle: subtitleFor(scope, filters, [`${rows.length} record(s)`]),
    columns: [
      { header: "Date", width: 12 },
      { header: "Learner", width: 28 },
      { header: "Grade", width: 12 },
      { header: "Section", width: 14 },
      { header: "Status", width: 12 },
      { header: "Reason / Remarks", width: 30 },
    ],
    rows: rows.map((r) => [
      formatLocalDateKey(r.date),
      r.learner.fullName,
      GRADE_LEVEL_LABELS[r.learner.gradeLevel.type] ?? r.learner.gradeLevel.type,
      r.learner.section?.name ?? "—",
      ATTENDANCE_STATUS_LABELS[r.status] ?? r.status,
      r.notes ?? "",
    ]),
  };
}

export async function buildReadingLevelTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTable> {
  const range = dateRange(filters);
  const rows = await prisma.readingLevelRecord.findMany({
    where: {
      ...(range ? { weekStart: range } : {}),
      learner: learnerWhere(scope, filters),
    },
    select: {
      weekStart: true,
      englishProfile: true,
      filipinoProfile: true,
      wordRecognitionLevel: true,
      readingComprehensionLevel: true,
      writingLevel: true,
      notes: true,
      learner: {
        select: {
          fullName: true,
          gradeLevel: { select: { type: true } },
          section: { select: { name: true } },
        },
      },
    },
    orderBy: [{ weekStart: "asc" }, { learner: { fullName: "asc" } }],
    take: 5000,
  });

  return {
    title: "Weekly Reading Level",
    subtitle: subtitleFor(scope, filters, [`${rows.length} assessment(s)`]),
    columns: [
      { header: "Period", width: 12 },
      { header: "Learner", width: 26 },
      { header: "Grade", width: 11 },
      { header: "Section", width: 12 },
      { header: "English", width: 22 },
      { header: "Filipino", width: 22 },
      { header: "Word Recognition", width: 18 },
      { header: "Comprehension", width: 18 },
      { header: "Writing", width: 16 },
      { header: "Remarks", width: 24 },
    ],
    rows: rows.map((r) => [
      formatLocalDateKey(r.weekStart),
      r.learner.fullName,
      GRADE_LEVEL_LABELS[r.learner.gradeLevel.type] ?? r.learner.gradeLevel.type,
      r.learner.section?.name ?? "—",
      READING_PROFILE_LABELS[r.englishProfile] ?? r.englishProfile,
      READING_PROFILE_LABELS[r.filipinoProfile] ?? r.filipinoProfile,
      r.wordRecognitionLevel
        ? (WEEKLY_WORD_RECOGNITION_LEVEL_LABELS[r.wordRecognitionLevel] ??
          r.wordRecognitionLevel)
        : "",
      r.readingComprehensionLevel
        ? (WEEKLY_READING_COMPREHENSION_LEVEL_LABELS[r.readingComprehensionLevel] ??
          r.readingComprehensionLevel)
        : "",
      r.writingLevel
        ? (WEEKLY_WRITING_LEVEL_LABELS[r.writingLevel] ?? r.writingLevel)
        : "",
      r.notes ?? "",
    ]),
  };
}

export async function buildTermGradesTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTable> {
  const rows = await prisma.termGrade.findMany({
    where: {
      ...(filters.schoolYearId ? { schoolYearId: filters.schoolYearId } : {}),
      ...(filters.term
        ? { term: filters.term as "FIRST" | "SECOND" | "THIRD" }
        : {}),
      learner: learnerWhere(scope, filters),
    },
    select: {
      term: true,
      subject: true,
      score: true,
      learner: {
        select: {
          id: true,
          fullName: true,
          gradeLevel: { select: { type: true } },
          section: { select: { name: true } },
        },
      },
    },
    orderBy: [{ learner: { fullName: "asc" } }],
    take: 10000,
  });

  // One row per learner per term, subjects across — the shape the DepEd sheet
  // is read in. A flat row-per-grade dump is unusable at a parent conference.
  const subjects = [...new Set(rows.map((r) => r.subject))].sort();
  type Group = {
    name: string;
    grade: string;
    section: string;
    term: string;
    scores: Map<string, number>;
  };
  const groups = new Map<string, Group>();

  for (const r of rows) {
    const key = `${r.learner.id}:${r.term}`;
    let g = groups.get(key);
    if (!g) {
      g = {
        name: r.learner.fullName,
        grade:
          GRADE_LEVEL_LABELS[r.learner.gradeLevel.type] ?? r.learner.gradeLevel.type,
        section: r.learner.section?.name ?? "—",
        term: TERM_PERIOD_LABELS[r.term] ?? r.term,
        scores: new Map(),
      };
      groups.set(key, g);
    }
    g.scores.set(r.subject, r.score);
  }

  return {
    title: "End of Term Report (Grades)",
    subtitle: subtitleFor(scope, filters, [`${groups.size} learner-term row(s)`]),
    columns: [
      { header: "Learner", width: 26 },
      { header: "Grade", width: 11 },
      { header: "Section", width: 12 },
      { header: "Term", width: 12 },
      ...subjects.map((s) => ({
        header: LEARNING_AREA_LABELS[s] ?? s,
        width: 12,
      })),
      { header: "General Average", width: 14 },
    ],
    rows: [...groups.values()].map((g) => {
      const scores = subjects.map((s) => g.scores.get(s) ?? null);
      const present = scores.filter((s): s is number => s !== null);
      const average =
        present.length > 0
          ? Math.round(present.reduce((a, b) => a + b, 0) / present.length)
          : null;
      return [g.name, g.grade, g.section, g.term, ...scores, average];
    }),
  };
}

export async function buildClassRosterTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTable> {
  const learners = await prisma.learner.findMany({
    where: learnerWhere(scope, filters),
    select: {
      fullName: true,
      gender: true,
      isAralLearner: true,
      gradeLevel: { select: { type: true } },
      section: { select: { name: true } },
    },
    orderBy: { fullName: "asc" },
    take: 5000,
  });

  return {
    title: "Class Roster",
    subtitle: subtitleFor(scope, filters, [`${learners.length} learner(s)`]),
    columns: [
      { header: "#", width: 6 },
      { header: "Learner", width: 30 },
      { header: "Grade", width: 14 },
      { header: "Section", width: 16 },
      { header: "Gender", width: 10 },
      { header: "ARAL", width: 8 },
    ],
    rows: learners.map((l, i) => [
      i + 1,
      l.fullName,
      GRADE_LEVEL_LABELS[l.gradeLevel.type] ?? l.gradeLevel.type,
      l.section?.name ?? "—",
      l.gender ?? "",
      l.isAralLearner ? "Yes" : "No",
    ]),
  };
}

/**
 * One row per class, aggregating what the three record reports show per learner:
 * headcount, attendance rate, and how many learners are reading at grade level.
 */
export async function buildTeacherSummaryTable(
  scope: ReportScope,
  filters: ReportFilters
): Promise<ReportTable> {
  const range = dateRange(filters);

  const sections = await prisma.section.findMany({
    where: {
      schoolId: scope.schoolId,
      deletedAt: null,
      ...(filters.sectionId ? { id: filters.sectionId } : {}),
      gradeLevel: {
        ...gradeWhere(scope),
        ...(filters.gradeLevelId ? { id: filters.gradeLevelId } : {}),
      },
    },
    select: {
      id: true,
      name: true,
      gradeLevel: { select: { type: true } },
      adviser: { select: { fullName: true } },
    },
    orderBy: { name: "asc" },
    take: 200,
  });

  const rows: (string | number | null)[][] = [];

  for (const section of sections) {
    const scopedLearners = {
      ...learnerWhere(scope, { ...filters, sectionId: section.id }),
    };

    const [learnerCount, aralCount, attendance, gradeReady] = await Promise.all([
      prisma.learner.count({ where: scopedLearners }),
      prisma.learner.count({ where: { ...scopedLearners, isAralLearner: true } }),
      prisma.attendance.groupBy({
        by: ["status"],
        where: {
          ...(range ? { date: range } : {}),
          learner: scopedLearners,
        },
        _count: { _all: true },
      }),
      prisma.readingLevelRecord.count({
        where: {
          ...(range ? { weekStart: range } : {}),
          learner: scopedLearners,
          englishProfile: "INDEPENDENT_GRADE_READY",
        },
      }),
    ]);

    const counts = new Map(attendance.map((a) => [a.status, a._count._all]));
    const present = (counts.get("PRESENT") ?? 0) + (counts.get("LATE") ?? 0);
    const absent = counts.get("ABSENT") ?? 0;
    const excused = counts.get("EXCUSED") ?? 0;
    const marked = present + absent + excused;
    // Guarded, not `|| 0`: a class with no marked days must read "—" rather
    // than 0%, which would be indistinguishable from perfect absenteeism.
    const rate = marked > 0 ? `${Math.round((present / marked) * 100)}%` : "—";

    rows.push([
      `${GRADE_LEVEL_LABELS[section.gradeLevel.type] ?? section.gradeLevel.type} - ${section.name}`,
      section.adviser?.fullName ?? "—",
      learnerCount,
      aralCount,
      present,
      absent,
      excused,
      rate,
      gradeReady,
    ]);
  }

  return {
    title: "Teacher Summary",
    subtitle: subtitleFor(scope, filters, [`${sections.length} class(es)`]),
    columns: [
      { header: "Class", width: 22 },
      { header: "Adviser", width: 24 },
      { header: "Learners", width: 10 },
      { header: "ARAL", width: 8 },
      { header: "Present", width: 10 },
      { header: "Absent", width: 10 },
      { header: "Excused", width: 10 },
      { header: "Attendance Rate", width: 14 },
      { header: "Grade-level Readers", width: 16 },
    ],
    rows,
  };
}
