/**
 * The shapes, copy and pure layout rules of the print template every export
 * carries (the School's End of Term Report layout: centred seal, DepEd header
 * lines, title, two info rows, table, signature block, bottom logos).
 *
 * Pure and client-safe on purpose: the printable learners report renders in a
 * client component, and importing these from `sheet-header.ts` (server-only,
 * Prisma) would break the client build. `sheet-header.ts` re-exports them.
 */

/** A DepEd-style "Label: Value" header line (School ID, School Year, ...). */
export type ReportHeaderField = { label: string; value: string };

/**
 * The two names the signature block prints: who prepared the report and the
 * School Head who notes it.
 */
export type ReportFooter = {
  /** The signed-in actor's display name. */
  preparedBy: string;
  /** The school's School Head, earliest-created if a school somehow has more than one. Blank, never a placeholder string, when the school has none on file. */
  notedBy: string;
};

/**
 * What an export is for.
 *
 * - `PRINT` (the default): the full template, laid out to print cleanly on A4.
 * - `RECORDS`: a plain data sheet — no merged cells, no images, no signature
 *   block — so it sorts, filters and re-imports cleanly. Excel only; a PDF is
 *   always the print template.
 */
export type ReportPurpose = "PRINT" | "RECORDS";

export const REPORT_PURPOSES: readonly ReportPurpose[] = ["PRINT", "RECORDS"];

export const DEFAULT_REPORT_PURPOSE: ReportPurpose = "PRINT";

/**
 * Everything the template needs to know about the school and the people on
 * the report, read once per export (`loadReportFrame` in `sheet-header.ts`).
 * Every field is a plain string; an unknown value is `""`, never a
 * placeholder.
 */
export type ReportFrame = {
  schoolName: string;
  schoolIdCode: string;
  region: string;
  division: string;
  district: string;
  address: string;
  schoolYearLabel: string;
  /** The School Head, for "Noted by". Blank when the school has none on file. */
  schoolHeadName: string;
  /** The signed-in actor, for "Prepared by" and "Generated by". */
  preparedBy: string;
};

export const EMPTY_REPORT_FRAME: ReportFrame = {
  schoolName: "",
  schoolIdCode: "",
  region: "",
  division: "",
  district: "",
  address: "",
  schoolYearLabel: "",
  schoolHeadName: "",
  preparedBy: "",
};

/**
 * The info row's grade/section cell. A report narrowed to one grade (and
 * maybe one section) names them; a wider one prints its scope label instead
 * ("All Classes").
 */
export type GradeSectionLine = {
  gradeLevel?: string | null;
  section?: string | null;
  /** Used when `gradeLevel` is unset. Defaults to "All Classes". */
  label?: string | null;
};

/**
 * The bottom logos for HTML, left to right, served from `public/brand/report/`.
 * Same images and order as `REPORT_BOTTOM_LOGOS` (`logo-data.ts`), which embeds
 * them as base64 for the Excel/PDF renderers.
 */
export const REPORT_BOTTOM_LOGO_SOURCES: readonly { src: string; alt: string }[] = [
  { src: "/brand/report/deped-wordmark.png", alt: "DepEd" },
  { src: "/brand/report/bagong-pilipinas.png", alt: "Bagong Pilipinas" },
  { src: "/brand/report/division-sarangani.png", alt: "DepEd Division of Sarangani" },
];

/**
 * @deprecated The pre-template single footer row (seal first, then the three
 * bottom logos). The printable learners report still renders it; new code
 * uses `REPORT_TOP_LOGO_SOURCE` + `REPORT_BOTTOM_LOGO_SOURCES`.
 */
export const REPORT_FOOTER_LOGO_SOURCES: readonly { src: string; alt: string }[] = [
  { src: "/brand/report/deped-seal.png", alt: "DepEd seal" },
  { src: "/brand/report/bagong-pilipinas.png", alt: "Bagong Pilipinas" },
  { src: "/brand/report/deped-wordmark.png", alt: "DepEd" },
  { src: "/brand/report/division-sarangani.png", alt: "DepEd Division of Sarangani" },
];

/** The seal centred above the header lines, for HTML. Same image as `REPORT_TOP_LOGO`. */
export const REPORT_TOP_LOGO_SOURCE: { src: string; alt: string } = {
  src: "/brand/report/deped-seal.png",
  alt: "Kagawaran ng Edukasyon seal",
};

export const SYSTEM_GENERATED_NOTE = "This is a system-generated report from LITRACK.";

export const SIGNATURE_CAPTION = "Signature over printed name";

// ---------------------------------------------------------------------------
// Pure layout rules, shared by the Excel and PDF renderers.
// ---------------------------------------------------------------------------

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

/**
 * "23 September 2026". Reads the Date's LOCAL calendar fields, so pass a
 * school-local day (`schoolToday()`), never a raw UTC instant.
 */
export function formatReportDate(date: Date): string {
  return `${date.getDate()} ${MONTH_NAMES[date.getMonth()]} ${date.getFullYear()}`;
}

/** A stored value an admin never filled in: blank, or a bracketed prompt like "[Enter region]". */
function clean(value: string | null | undefined): string {
  const v = (value ?? "").trim();
  if (!v) return "";
  if (/^\[.*\]$/.test(v)) return "";
  return v;
}

/** Prefixes `prefix` unless the value already starts with one of `already`. */
function prefixed(value: string, prefix: string, already: RegExp): string {
  return already.test(value) ? value : `${prefix}${value}`;
}

export type TemplateHeaderLine = {
  text: string;
  bold?: boolean;
  size: number;
  /** ARGB. */
  color: string;
};

export const TEMPLATE_INK = "FF172B42";
export const TEMPLATE_BLUE = "FF2362A0";
export const TEMPLATE_NAVY = "FF17365D";
export const TEMPLATE_MUTED = "FF64748B";

/**
 * The centred lines under the seal, in order. A line whose value the school
 * has not filled in is omitted rather than printed as a placeholder.
 */
export function templateHeaderLines(frame: ReportFrame): TemplateHeaderLine[] {
  const lines: TemplateHeaderLine[] = [
    { text: "Republic of the Philippines", size: 11, color: TEMPLATE_INK },
    { text: "DEPARTMENT OF EDUCATION", bold: true, size: 16, color: TEMPLATE_INK },
  ];
  const region = clean(frame.region);
  if (region) {
    lines.push({
      text: prefixed(region, "Region ", /^region\b/i),
      size: 11,
      color: TEMPLATE_BLUE,
    });
  }
  const division = clean(frame.division);
  if (division) {
    lines.push({
      text: prefixed(division, "Schools Division of ", /^(schools\s+)?division\b/i),
      size: 11,
      color: TEMPLATE_BLUE,
    });
  }
  const district = clean(frame.district);
  if (district) {
    lines.push({
      text: prefixed(district, "District: ", /^district\b/i),
      size: 11,
      color: TEMPLATE_BLUE,
    });
  }
  const school = clean(frame.schoolName);
  if (school) lines.push({ text: school, bold: true, size: 12, color: TEMPLATE_INK });
  const address = clean(frame.address);
  if (address) {
    lines.push({ text: `School Address: ${address}`, size: 11, color: TEMPLATE_BLUE });
  }
  return lines;
}

/** "Grade Level: Grade 3    /    Section: A", or the scope label. */
export function formatGradeSectionLine(line: GradeSectionLine | undefined): string {
  if (line?.gradeLevel) {
    return `Grade Level: ${line.gradeLevel}    /    Section: ${line.section || "All Sections"}`;
  }
  return line?.label || "All Classes";
}

/** The two info rows: [School ID, School Year, Report Date] and [grade/section, reporting period]. */
export function templateInfoRows(args: {
  frame: ReportFrame;
  gradeSection?: GradeSectionLine;
  reportingPeriod?: string;
  reportDate: Date;
}): { first: [string, string, string]; second: [string, string] } {
  return {
    first: [
      `School ID: ${clean(args.frame.schoolIdCode) || "—"}`,
      `School Year: ${clean(args.frame.schoolYearLabel) || "—"}`,
      `Report Date: ${formatReportDate(args.reportDate)}`,
    ],
    second: [
      formatGradeSectionLine(args.gradeSection),
      `Reporting Period: ${args.reportingPeriod || `As of ${formatReportDate(args.reportDate)}`}`,
    ],
  };
}

/**
 * Splits `count` columns into contiguous 1-based groups sized by `fractions`
 * (which should sum to 1). Every group gets at least one column when
 * `count >= fractions.length`.
 */
export function splitColumns(count: number, fractions: number[]): [number, number][] {
  const k = fractions.length;
  const out: [number, number][] = [];
  let start = 1;
  let cumulative = 0;
  for (let i = 0; i < k; i++) {
    cumulative += fractions[i]!;
    let end = i === k - 1 ? count : Math.round(count * cumulative);
    end = Math.max(end, start); // at least one column
    end = Math.min(end, count - (k - 1 - i)); // leave one for every later group
    end = Math.max(end, start);
    out.push([start, end]);
    start = end + 1;
  }
  return out;
}

/** The signature block's three groups, with a spacer column between each when there is room. */
export function signatureGroups(count: number): [number, number][] {
  if (count >= 5) {
    const inner = splitColumns(count - 2, [1 / 3, 1 / 3, 1 / 3]);
    return inner.map(([a, b], i) => [a + i, b + i] as [number, number]);
  }
  return splitColumns(count, [1 / 3, 1 / 3, 1 / 3]);
}

/**
 * The fields the printable (HTML) learners report shows at its top, derived
 * from the same frame the spreadsheets use.
 */
export function frameHeaderFields(
  frame: ReportFrame,
  gradeSection: string
): ReportHeaderField[] {
  const fields: ReportHeaderField[] = [
    { label: "School ID", value: clean(frame.schoolIdCode) || "—" },
    { label: "School Name", value: clean(frame.schoolName) || "—" },
  ];
  if (clean(frame.region)) fields.push({ label: "Region", value: clean(frame.region) });
  if (clean(frame.division)) fields.push({ label: "Division", value: clean(frame.division) });
  if (clean(frame.district)) fields.push({ label: "District", value: clean(frame.district) });
  fields.push(
    { label: "School Year", value: clean(frame.schoolYearLabel) || "—" },
    { label: "Grade / Section", value: gradeSection },
    { label: "Prepared by", value: frame.preparedBy }
  );
  return fields;
}

/** The two signature names, in the shape the printable report takes. */
export function frameFooter(frame: ReportFrame): ReportFooter {
  return { preparedBy: frame.preparedBy, notedBy: frame.schoolHeadName };
}
