import "server-only";

import type { Cell, Workbook, Worksheet } from "exceljs";
import { prisma } from "@/lib/prisma";
import { formatLocalDateKey } from "@/lib/date-keys";
import { REPORT_BOTTOM_LOGOS, REPORT_TOP_LOGO } from "@/lib/reports/logo-data";
import {
  SIGNATURE_CAPTION,
  SYSTEM_GENERATED_NOTE,
  TEMPLATE_INK,
  TEMPLATE_MUTED,
  TEMPLATE_NAVY,
  signatureGroups,
  splitColumns,
  templateHeaderLines,
  templateInfoRows,
  type GradeSectionLine,
  type ReportFooter,
  type ReportFrame,
  type ReportHeaderField,
  type ReportPurpose,
} from "@/lib/reports/report-frame";

/**
 * The ONE implementation of the School's End of Term Report print template
 * for Excel, and its plain RECORDS counterpart. Every Excel-producing path —
 * the Reports Hub (`render.ts`), the learner exports, term grades and the
 * Kindergarten checklist — builds a `TemplateSheet` and hands it here, so the
 * frame never has a second, drifting copy.
 *
 * `loadReportFrame` is the only Prisma in this module: three schoolId-pinned
 * reads (School, SchoolYear, the School Head), made once per export.
 */

// Types and copy live in the client-safe `report-frame.ts`; re-exported so
// server callers keep one import.
export {
  SYSTEM_GENERATED_NOTE,
  type GradeSectionLine,
  type ReportFooter,
  type ReportFrame,
  type ReportHeaderField,
  type ReportPurpose,
};

export type LoadReportFrameArgs = {
  schoolId: string;
  /** Pins the School Year row to this id (still scoped to `schoolId`); omitted or null falls back to the school's active year. */
  schoolYearId?: string | null;
  /** The signed-in actor's display name ("Prepared by", "Generated by"). */
  preparedBy: string;
  /** School name the caller already resolved, used if the fresh School read comes back empty. */
  schoolName?: string | null;
};

/**
 * Everything the template prints about the school and its people. Three
 * reads, all pinned to `schoolId`; a school with no School Head on file (mid-
 * onboarding, or between heads) leaves "Noted by" blank rather than guessing.
 */
export async function loadReportFrame(args: LoadReportFrameArgs): Promise<ReportFrame> {
  const [school, schoolYear, schoolHead] = await Promise.all([
    prisma.school.findFirst({
      where: { id: args.schoolId, deletedAt: null },
      select: {
        schoolIdCode: true,
        name: true,
        region: true,
        division: true,
        district: true,
        address: true,
      },
    }),
    prisma.schoolYear.findFirst({
      where: {
        schoolId: args.schoolId,
        ...(args.schoolYearId ? { id: args.schoolYearId } : { isActive: true }),
      },
      select: { label: true },
    }),
    prisma.user.findFirst({
      where: { schoolId: args.schoolId, role: "SCHOOL_HEAD", deletedAt: null },
      orderBy: { createdAt: "asc" },
      select: { fullName: true },
    }),
  ]);

  return {
    schoolName: school?.name ?? args.schoolName ?? "",
    schoolIdCode: school?.schoolIdCode ?? "",
    region: school?.region ?? "",
    division: school?.division ?? "",
    district: school?.district ?? "",
    address: school?.address ?? "",
    schoolYearLabel: schoolYear?.label ?? "",
    schoolHeadName: schoolHead?.fullName ?? "",
    preparedBy: args.preparedBy,
  };
}

export type TemplateCell = string | number | null;

/** One data sheet, in either purpose. */
export type TemplateSheet = {
  /** The report's title: footer line, page footer, RECORDS line 1. */
  reportTitle: string;
  /** The title row's text when it differs from `reportTitle` (a block heading). Printed uppercase. */
  sheetTitle?: string;
  gradeSection?: GradeSectionLine;
  /** "First Term (Aug–Oct)", "2026-08-24 to 2026-08-28", "As of 23 September 2026". */
  reportingPeriod?: string;
  columns: { header: string; width?: number }[];
  rows: TemplateCell[][];
  /** Count / notes lines printed under the table. */
  summary?: string[];
  /** A block's own annotation (SF2 legend), printed with the summary. */
  note?: string;
  /** 0-based row indices drawn bold with a light fill (SF2 totals, sex headers). */
  boldRowIndices?: number[];
  /** Parallel to `rows`: a `true` cell gets the grey "no record" fill. */
  shadedCells?: boolean[][];
  /** Leading columns frozen alongside the header row. */
  freezeColumns?: number;
  /** 0-based index of the name column: left-aligned, at least 28 wide. Defaults to the first column not headed "#". */
  primaryColumn?: number;
};

export type TemplateContext = {
  frame: ReportFrame;
  /** The school-local day the report is generated on (`schoolToday()`). */
  generatedOn: Date;
};

// ---------------------------------------------------------------------------
// Style constants (ARGB).
// ---------------------------------------------------------------------------

const FONT = "Arial";
const HEADER_FILL = "FF17365D";
const INFO_FILL = "FFFFF2CC";
const DATA_FILL = "FFF0F4F8";
const DATA_RULE = "FFCBD5E1";
const TOTAL_FILL = "FFE2E8F0";
const SHADED_FILL = "FFD9D9D9";
const WHITE = "FFFFFFFF";
const RECORDS_HEADER_FILL = "FFE2E8F0";

const DEFAULT_COL_WIDTH = 18;
const EXTRA_COL_WIDTH = 12;
const PRIMARY_MIN_WIDTH = 28;
/** Header, info and signature rows need at least this many columns to lay out. */
const MIN_TEMPLATE_COLUMNS = 3;

const EMU_PER_PX = 9525;
const SEAL_PX = 100;
const SEAL_TOP_PX = 10;
const BOTTOM_LOGO_PX = 78;
const BOTTOM_LOGO_GAP_PX = 8;
const BOTTOM_LOGO_TOP_PX = 4;

function solid(argb: string) {
  return { type: "pattern" as const, pattern: "solid" as const, fgColor: { argb } };
}

function font(size: number, color: string, extra: { bold?: boolean; italic?: boolean } = {}) {
  return { name: FONT, size, color: { argb: color }, ...extra };
}

// ---------------------------------------------------------------------------
// Images: decoded once per process, registered once per workbook.
// ---------------------------------------------------------------------------

type DecodedLogo = { buffer: Buffer; width: number; height: number };

/** Logo bytes decoded once per process, not once per sheet. */
export const TOP_LOGO: DecodedLogo = {
  buffer: Buffer.from(REPORT_TOP_LOGO.base64, "base64"),
  width: SEAL_PX,
  height: SEAL_PX,
};

export const BOTTOM_LOGOS: DecodedLogo[] = REPORT_BOTTOM_LOGOS.map((logo) => ({
  buffer: Buffer.from(logo.base64, "base64"),
  width: Math.round((BOTTOM_LOGO_PX / logo.height) * logo.width),
  height: BOTTOM_LOGO_PX,
}));

/**
 * Each workbook registers the four logo files once and reuses the ids on
 * every sheet, so a 12-month SF2 export embeds four images, not forty-eight.
 */
const workbookLogoIds = new WeakMap<Workbook, { top: number; bottom: number[] }>();

function logoIds(wb: Workbook): { top: number; bottom: number[] } {
  let ids = workbookLogoIds.get(wb);
  if (!ids) {
    // The cast is exceljs's own wart: its declarations open with
    // `declare interface Buffer extends ArrayBuffer {}` (`node_modules/exceljs/index.d.ts:1`),
    // which leaves a real `Buffer` unassignable to the field asking for one.
    const add = (logo: DecodedLogo) =>
      wb.addImage({
        buffer: logo.buffer as unknown as Parameters<Workbook["addImage"]>[0]["buffer"],
        extension: "png",
      });
    ids = { top: add(TOP_LOGO), bottom: BOTTOM_LOGOS.map(add) };
    workbookLogoIds.set(wb, ids);
  }
  return ids;
}

/** Excel draws a column `w` characters wide as `floor(w * 7 + 5)` px. */
function columnPx(width: number): number {
  return Math.floor(width * 7 + 5);
}

/**
 * A fixed-pixel image anchor. ExcelJS's fractional `{ col, row }` anchors
 * convert offsets with their own unit guess, which lands images in the wrong
 * place; the native form states the cell and an EMU offset exactly.
 */
function nativeAnchor(widthsPx: number[], xPx: number, row0: number, yPx: number) {
  let left = 0;
  let col = widthsPx.length - 1;
  let off = 0;
  for (let i = 0; i < widthsPx.length; i++) {
    if (xPx < left + widthsPx[i]!) {
      col = i;
      off = Math.max(0, xPx - left);
      break;
    }
    left += widthsPx[i]!;
  }
  return {
    nativeCol: col,
    nativeColOff: Math.round(off * EMU_PER_PX),
    nativeRow: row0,
    nativeRowOff: Math.round(yPx * EMU_PER_PX),
  } as unknown as { col: number; row: number };
}

// ---------------------------------------------------------------------------
// Column widths.
// ---------------------------------------------------------------------------

function defaultPrimaryColumn(columns: { header: string }[]): number {
  const idx = columns.findIndex((c) => c.header.trim() !== "#");
  return idx === -1 ? 0 : idx;
}

/** Wide enough that the bold header never wraps past three lines. */
function headerMinWidth(header: string): number {
  const words = header.split(/\s+/).filter(Boolean);
  const longest = words.reduce((m, w) => Math.max(m, w.length), 0);
  const perLine = Math.ceil(header.length / 3);
  return Math.ceil(Math.max(longest, perLine) * 1.2) + 1;
}

function templateWidths(sheet: TemplateSheet, templateCols: number): number[] {
  const primary = sheet.primaryColumn ?? defaultPrimaryColumn(sheet.columns);
  return Array.from({ length: templateCols }, (_, i) => {
    const col = sheet.columns[i];
    if (!col) return EXTRA_COL_WIDTH;
    let w = Math.max(col.width ?? DEFAULT_COL_WIDTH, headerMinWidth(col.header));
    if (i === primary) w = Math.max(w, PRIMARY_MIN_WIDTH);
    return w;
  });
}

// ---------------------------------------------------------------------------
// Row helpers.
// ---------------------------------------------------------------------------

type CellStyle = Partial<Pick<Cell, "font" | "fill" | "alignment" | "border">>;

function styleRange(ws: Worksheet, row: number, from: number, to: number, style: CellStyle) {
  for (let c = from; c <= to; c++) {
    const cell = ws.getRow(row).getCell(c);
    if (style.font) cell.font = style.font;
    if (style.fill) cell.fill = style.fill;
    if (style.alignment) cell.alignment = style.alignment;
    if (style.border) cell.border = style.border;
  }
}

/** Writes `text` into `from`, styles the whole span, and merges it when wider than one cell. */
function mergedText(
  ws: Worksheet,
  row: number,
  from: number,
  to: number,
  text: string,
  style: CellStyle
) {
  ws.getRow(row).getCell(from).value = text;
  styleRange(ws, row, from, to, style);
  if (to > from) ws.mergeCells(row, from, row, to);
}

function blankRow(ws: Worksheet, height?: number): number {
  const row = ws.addRow([]);
  if (height) row.height = height;
  return row.number;
}

function colLetter(ws: Worksheet, col: number): string {
  return ws.getColumn(col).letter;
}

/** `&` is Excel's header/footer control character; a literal one is doubled. */
function escapeHeaderFooter(text: string): string {
  return text.replace(/&/g, "&&");
}

/** Rough wrapped-line count for a merged text cell `widthChars` wide. */
function wrappedLines(text: string, widthChars: number): number {
  return Math.max(1, Math.ceil((text.length * 1.1) / Math.max(widthChars, 1)));
}

// ---------------------------------------------------------------------------
// PRINT.
// ---------------------------------------------------------------------------

/**
 * Draws one full print-template sheet onto an EMPTY worksheet: seal, header
 * lines, rule, title, info rows, table, summary, signature block, rule,
 * bottom logos with the generated lines, then page setup. Returns the table
 * header's row number.
 */
export function writePrintSheet(
  wb: Workbook,
  ws: Worksheet,
  ctx: TemplateContext,
  sheet: TemplateSheet
): number {
  const n = sheet.columns.length;
  const cols = Math.max(n, MIN_TEMPLATE_COLUMNS);
  const widths = templateWidths(sheet, cols);
  widths.forEach((w, i) => {
    ws.getColumn(i + 1).width = w;
  });
  const widthsPx = widths.map(columnPx);
  const totalChars = widths.reduce((a, b) => a + b, 0);
  const center = { horizontal: "center" as const, vertical: "middle" as const, wrapText: true };
  const left = { horizontal: "left" as const, vertical: "middle" as const, wrapText: true };
  const primary = sheet.primaryColumn ?? defaultPrimaryColumn(sheet.columns);

  // Row 1: the seal, drawn after widths are final so its centre is right.
  blankRow(ws, 90);

  // Rows 2..: the centred header lines.
  for (const line of templateHeaderLines(ctx.frame)) {
    const r = blankRow(ws, 23);
    mergedText(ws, r, 1, cols, line.text, {
      font: font(line.size, line.color, { bold: line.bold }),
      alignment: center,
    });
  }

  // The rule under the header.
  const ruleTop = blankRow(ws, 6);
  styleRange(ws, ruleTop, 1, cols, {
    border: { bottom: { style: "medium", color: { argb: TEMPLATE_NAVY } } },
  });

  // Title.
  const titleRow = blankRow(ws, 30);
  mergedText(ws, titleRow, 1, cols, (sheet.sheetTitle ?? sheet.reportTitle).toUpperCase(), {
    font: font(14, TEMPLATE_INK, { bold: true }),
    alignment: center,
  });
  blankRow(ws);

  // Info rows.
  const info = templateInfoRows({
    frame: ctx.frame,
    gradeSection: sheet.gradeSection,
    reportingPeriod: sheet.reportingPeriod,
    reportDate: ctx.generatedOn,
  });
  const info1 = blankRow(ws, 23);
  splitColumns(cols, [0.4, 0.3, 0.3]).forEach(([a, b], i) => {
    mergedText(ws, info1, a, b, info.first[i]!, {
      font: font(11, TEMPLATE_INK, { bold: true }),
      fill: solid(INFO_FILL),
      alignment: center,
    });
  });
  const info2 = blankRow(ws, 23);
  splitColumns(cols, [0.4, 0.6]).forEach(([a, b], i) => {
    mergedText(ws, info2, a, b, info.second[i]!, {
      font: font(11, TEMPLATE_INK, { bold: true }),
      alignment: center,
    });
  });
  blankRow(ws);

  // Table header.
  const headerRowNum = ws.addRow(sheet.columns.map((c) => c.header)).number;
  const headerRow = ws.getRow(headerRowNum);
  headerRow.height = 40;
  const whiteSide = { style: "thin" as const, color: { argb: WHITE } };
  styleRange(ws, headerRowNum, 1, n, {
    font: font(11, WHITE, { bold: true }),
    fill: solid(HEADER_FILL),
    alignment: center,
    border: { left: whiteSide, right: whiteSide },
  });

  // Data rows.
  const boldRows = new Set(sheet.boldRowIndices ?? []);
  const averageCol = sheet.columns.findIndex((c) => /general average/i.test(c.header));
  const rule = { bottom: { style: "thin" as const, color: { argb: DATA_RULE } } };
  sheet.rows.forEach((values, rowIdx) => {
    const row = ws.addRow(values.map((v) => (v === null ? "" : v)));
    row.height = 22;
    const isBold = boldRows.has(rowIdx);
    for (let c = 1; c <= n; c++) {
      const cell = row.getCell(c);
      const shaded = !isBold && sheet.shadedCells?.[rowIdx]?.[c - 1];
      cell.font = font(11, TEMPLATE_INK, { bold: isBold || c - 1 === averageCol });
      cell.fill = solid(isBold ? TOTAL_FILL : shaded ? SHADED_FILL : DATA_FILL);
      cell.border = rule;
      cell.alignment = {
        horizontal: c - 1 === primary ? "left" : "center",
        vertical: "middle",
      };
      if (typeof cell.value === "number" && Number.isInteger(cell.value)) cell.numFmt = "0";
    }
  });

  // Summary + note.
  const summaryLines = [...(sheet.summary ?? []), ...(sheet.note ? [sheet.note] : [])];
  if (summaryLines.length > 0) {
    blankRow(ws);
    for (const line of summaryLines) {
      const r = blankRow(ws);
      const lines = wrappedLines(line, totalChars);
      if (lines > 1) ws.getRow(r).height = 15 * lines;
      mergedText(ws, r, 1, cols, line, { font: font(11, TEMPLATE_INK), alignment: left });
    }
  }

  // Signature block.
  blankRow(ws);
  blankRow(ws);
  const groups = signatureGroups(cols);
  const labels = ["Prepared by:", "Checked by:", "Noted by:"];
  const names = [ctx.frame.preparedBy, "", ctx.frame.schoolHeadName];
  const labelRow = blankRow(ws, 20);
  groups.forEach(([a, b], i) =>
    mergedText(ws, labelRow, a, b, labels[i]!, {
      font: font(11, TEMPLATE_INK, { bold: true }),
      alignment: center,
    })
  );
  blankRow(ws, 28);
  const nameRow = blankRow(ws, 20);
  groups.forEach(([a, b], i) =>
    mergedText(ws, nameRow, a, b, names[i]!, {
      font: font(11, TEMPLATE_INK, { bold: true }),
      alignment: center,
      border: { bottom: { style: "thin", color: { argb: TEMPLATE_MUTED } } },
    })
  );
  const captionRow = blankRow(ws, 16);
  groups.forEach(([a, b]) =>
    mergedText(ws, captionRow, a, b, SIGNATURE_CAPTION, {
      font: font(9, TEMPLATE_MUTED),
      alignment: center,
    })
  );

  // Rule, then the footer rows.
  blankRow(ws);
  const ruleBottom = blankRow(ws, 6);
  styleRange(ws, ruleBottom, 1, cols, {
    border: { bottom: { style: "thin", color: { argb: TEMPLATE_NAVY } } },
  });

  const logosPx =
    BOTTOM_LOGOS.reduce((sum, l) => sum + l.width, 0) +
    BOTTOM_LOGO_GAP_PX * BOTTOM_LOGOS.length;
  let textStart = cols;
  let edge = 0;
  for (let c = 1; c <= cols; c++) {
    if (edge >= logosPx) {
      textStart = c;
      break;
    }
    edge += widthsPx[c - 1]!;
  }
  textStart = Math.min(cols, Math.max(textStart, Math.floor(cols * 0.4) + 1));
  const footerLines = [
    `LITRACK | ${sheet.reportTitle}`,
    `Generated by ${ctx.frame.preparedBy} on ${formatLocalDateKey(ctx.generatedOn)}`,
    SYSTEM_GENERATED_NOTE,
  ];
  const firstFooterRow = ws.rowCount + 1;
  for (const line of footerLines) {
    const r = blankRow(ws, 22);
    mergedText(ws, r, textStart, cols, line, {
      font: font(9, TEMPLATE_MUTED),
      alignment: { horizontal: "right", vertical: "middle" },
    });
  }
  const lastRow = ws.rowCount;

  // Images, all at fixed pixel sizes.
  const ids = logoIds(wb);
  const tablePx = widthsPx.reduce((a, b) => a + b, 0);
  ws.addImage(ids.top, {
    tl: nativeAnchor(widthsPx, Math.max(0, Math.round(tablePx / 2 - SEAL_PX / 2)), 0, SEAL_TOP_PX),
    ext: { width: TOP_LOGO.width, height: TOP_LOGO.height },
  });
  let x = 0;
  BOTTOM_LOGOS.forEach((logo, i) => {
    ws.addImage(ids.bottom[i]!, {
      tl: nativeAnchor(widthsPx, x, firstFooterRow - 1, BOTTOM_LOGO_TOP_PX),
      ext: { width: logo.width, height: logo.height },
    });
    x += logo.width + BOTTOM_LOGO_GAP_PX;
  });

  // Page setup.
  const lastCol = colLetter(ws, cols);
  ws.pageSetup = {
    ...ws.pageSetup,
    paperSize: 9,
    orientation: n > 6 ? "landscape" : "portrait",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    horizontalCentered: true,
    showGridLines: false,
    margins: { left: 0.25, right: 0.25, top: 0.3, bottom: 0.3, header: 0.15, footer: 0.15 },
    printArea: `A1:${lastCol}${lastRow}`,
    printTitlesRow: `${headerRowNum}:${headerRowNum}`,
  };
  ws.headerFooter = {
    ...ws.headerFooter,
    oddFooter: `&L LITRACK&C ${escapeHeaderFooter(sheet.reportTitle)}&R Page &P of &N`,
  };
  // No frozen panes on a print sheet: the table header sits ~15 rows down,
  // under the seal and letterhead, and freezing there pins most of a laptop
  // screen. Printing repeats the header via `printTitlesRow` above instead.
  ws.views = [{ state: "normal", showGridLines: false }];

  return headerRowNum;
}

// ---------------------------------------------------------------------------
// RECORDS.
// ---------------------------------------------------------------------------

/**
 * A plain data sheet: one identifying line, a blank row, the header at row 3,
 * then the rows. No merged cells, no images, no signature block — nothing
 * that stops Excel sorting, filtering or re-importing it.
 */
export function writeRecordsSheet(ws: Worksheet, ctx: TemplateContext, sheet: TemplateSheet): number {
  const title = sheet.sheetTitle ? `${sheet.reportTitle} — ${sheet.sheetTitle}` : sheet.reportTitle;
  const school = ctx.frame.schoolName || "School";
  ws.addRow([
    `${school} — ${title} — generated ${formatLocalDateKey(ctx.generatedOn)} by ${ctx.frame.preparedBy}`,
  ]).font = { bold: true };
  ws.addRow([]);

  const headerRowNum = ws.addRow(sheet.columns.map((c) => c.header)).number;
  styleRange(ws, headerRowNum, 1, sheet.columns.length, {
    font: { bold: true },
    fill: solid(RECORDS_HEADER_FILL),
  });

  const boldRows = new Set(sheet.boldRowIndices ?? []);
  sheet.rows.forEach((values, rowIdx) => {
    const row = ws.addRow(values.map((v) => (v === null ? "" : v)));
    if (boldRows.has(rowIdx)) row.font = { bold: true };
    sheet.shadedCells?.[rowIdx]?.forEach((shaded, c) => {
      if (shaded) row.getCell(c + 1).fill = solid(SHADED_FILL);
    });
  });

  sheet.columns.forEach((c, i) => {
    ws.getColumn(i + 1).width = c.width ?? DEFAULT_COL_WIDTH;
  });

  if (sheet.columns.length > 0) {
    ws.autoFilter = {
      from: { row: headerRowNum, column: 1 },
      to: { row: headerRowNum + sheet.rows.length, column: sheet.columns.length },
    };
  }
  ws.views = [
    { state: "frozen", xSplit: sheet.freezeColumns ?? 0, ySplit: headerRowNum },
  ];
  return headerRowNum;
}

/** Draws `sheet` onto `ws` in the requested purpose. */
export function writeTemplateSheet(
  wb: Workbook,
  ws: Worksheet,
  ctx: TemplateContext,
  sheet: TemplateSheet,
  purpose: ReportPurpose
): number {
  return purpose === "RECORDS"
    ? writeRecordsSheet(ws, ctx, sheet)
    : writePrintSheet(wb, ws, ctx, sheet);
}
