import "server-only";

import type { Workbook, Worksheet } from "exceljs";
import { prisma } from "@/lib/prisma";
import { REPORT_FOOTER_LOGOS } from "@/lib/reports/logo-data";

/**
 * The single shared DepEd-style header block every generated Excel sheet (and
 * the Reports Hub's PDF) opens with:
 *
 *   School ID:        <code>
 *   School Name:      <name>
 *   Region:           <region>        (omitted when the school has none on file)
 *   Division:         <division>      (omitted when the school has none on file)
 *   District:         <district>      (omitted when the school has none on file)
 *   School Year:      <label>
 *   Grade / Section:  <scope label, or "All"/"All Classes">
 *   Prepared by:      <actor>
 *   <blank row>
 *   <subtitle lines>
 *   <blank row>
 *
 * `loadReportHeader` resolves the fields (one schoolId-pinned `School` read,
 * one schoolId-pinned `SchoolYear` read); `writeSheetHeader` draws them onto a
 * worksheet exactly as above and leaves the cursor ready for the caller's own
 * table header row. Both the Reports Hub (`render.ts`, `queries.ts`) and every
 * other Excel-producing action (`export-learners.ts`, `term-grades.ts`,
 * `kinder-competencies.ts`) go through these two functions so the block never
 * has a second, drifting copy.
 */

// Types and copy live in the client-safe `report-frame.ts`; re-exported so
// server callers keep one import.
import {
  SYSTEM_GENERATED_NOTE,
  type ReportFooter,
  type ReportHeaderField,
} from "@/lib/reports/report-frame";
export { SYSTEM_GENERATED_NOTE, type ReportFooter, type ReportHeaderField };

export type LoadReportHeaderArgs = {
  schoolId: string;
  /** Pins the School Year row to this id (still scoped to `schoolId`); omitted or null falls back to the school's active year. */
  schoolYearId?: string | null;
  /** "Grade 3 - A" / "Grade 3" / "All Classes" / "All" — the caller decides the fallback word, since the hub and the plain exports disagree on it. */
  gradeSectionLabel?: string | null;
  /** The signed-in actor's display name ("Prepared by"). */
  preparedBy: string;
  /** School name the caller already resolved, used if the fresh School read comes back empty. */
  schoolName?: string | null;
};

/** The same header with its "Grade / Section" value swapped — for one read shared across per-section sheets. */
export function withGradeSection(
  header: ReportHeaderField[],
  gradeSectionLabel: string
): ReportHeaderField[] {
  return header.map((f) =>
    f.label === "Grade / Section" ? { ...f, value: gradeSectionLabel } : f
  );
}

/**
 * One schoolId-pinned `School` read and one schoolId-pinned `SchoolYear`
 * read — the only two Prisma calls in this module. Every field beyond those
 * two reads is supplied by the caller, who already knows its own scope
 * (grade/section) and who is asking (the signed-in actor).
 */
export async function loadReportHeader(
  args: LoadReportHeaderArgs
): Promise<ReportHeaderField[]> {
  const [school, schoolYear] = await Promise.all([
    prisma.school.findFirst({
      where: { id: args.schoolId, deletedAt: null },
      select: { schoolIdCode: true, name: true, region: true, division: true, district: true },
    }),
    prisma.schoolYear.findFirst({
      where: {
        schoolId: args.schoolId,
        ...(args.schoolYearId ? { id: args.schoolYearId } : { isActive: true }),
      },
      select: { label: true },
    }),
  ]);

  const fields: ReportHeaderField[] = [
    { label: "School ID", value: school?.schoolIdCode ?? "—" },
    { label: "School Name", value: school?.name ?? args.schoolName ?? "—" },
  ];
  if (school?.region) fields.push({ label: "Region", value: school.region });
  if (school?.division) fields.push({ label: "Division", value: school.division });
  if (school?.district) fields.push({ label: "District", value: school.district });
  fields.push(
    { label: "School Year", value: schoolYear?.label ?? "—" },
    { label: "Grade / Section", value: args.gradeSectionLabel ?? "All" },
    { label: "Prepared by", value: args.preparedBy }
  );
  return fields;
}

/**
 * Draws the header fields (bold labels), a blank row, the subtitle lines, and
 * a trailing blank row onto `ws`, in that exact order. Returns the number of
 * the LAST row written, so the caller's own table header goes at the return
 * value + 1 (`ws.addRow(...)` right after also lands there on its own, since
 * ExcelJS worksheets always append — the return value is for callers, like
 * `render.ts`, that need to know the row number to freeze panes below).
 *
 * `subtitleLines` is a parameter, not read off any shared state, because only
 * the FIRST sheet of a multi-sheet report carries the subtitle (school name,
 * filters, "Generated by … on …") — every later sheet repeats the header
 * fields but not the subtitle. A caller with nothing to say passes `[]`.
 */
export function writeSheetHeader(
  ws: Worksheet,
  header: ReportHeaderField[],
  subtitleLines: string[] = []
): number {
  for (const field of header) {
    const row = ws.addRow([`${field.label}:`, field.value]);
    row.getCell(1).font = { bold: true };
  }
  ws.addRow([]);
  for (const line of subtitleLines) {
    ws.addRow([line]);
  }
  if (subtitleLines.length > 0) ws.addRow([]);
  return ws.rowCount;
}


/**
 * One schoolId-pinned `User` read: the school's School Head. A school with no
 * School Head on file (mid-onboarding, or between heads) leaves `notedBy`
 * blank rather than guessing — the same "state a report renders, never an
 * error" rule `buildMosyTable` follows for an unresolved window.
 */
export async function loadReportFooter(args: {
  schoolId: string;
  preparedBy: string;
}): Promise<ReportFooter> {
  const schoolHead = await prisma.user.findFirst({
    where: { schoolId: args.schoolId, role: "SCHOOL_HEAD", deletedAt: null },
    orderBy: { createdAt: "asc" },
    select: { fullName: true },
  });
  return { preparedBy: args.preparedBy, notedBy: schoolHead?.fullName ?? "" };
}

/** Every footer logo is drawn this tall, side by side, width kept to aspect. */
export const FOOTER_LOGO_HEIGHT = 30;
const FOOTER_LOGO_GAP = 6;

/** Logo bytes decoded once per process, not once per sheet. */
export const FOOTER_LOGO_BUFFERS = REPORT_FOOTER_LOGOS.map((logo) => ({
  buffer: Buffer.from(logo.base64, "base64"),
  width: Math.round((FOOTER_LOGO_HEIGHT / logo.height) * logo.width),
}));

/**
 * Each workbook registers the logo bytes once and reuses the ids on every
 * sheet, so a 12-month SF2 export embeds four images, not forty-eight.
 */
const workbookLogoIds = new WeakMap<Workbook, number[]>();

function footerLogoIds(wb: Workbook): number[] {
  let ids = workbookLogoIds.get(wb);
  if (!ids) {
    // The cast is exceljs's own wart: its declarations open with
    // `declare interface Buffer extends ArrayBuffer {}` (`node_modules/exceljs/index.d.ts:1`),
    // which leaves a real `Buffer` unassignable to the field asking for one.
    ids = FOOTER_LOGO_BUFFERS.map((logo) =>
      wb.addImage({
        buffer: logo.buffer as unknown as Parameters<Workbook["addImage"]>[0]["buffer"],
        extension: "png",
      })
    );
    workbookLogoIds.set(wb, ids);
  }
  return ids;
}

/**
 * A pixel offset from the sheet's left edge as a fractional column index, the
 * unit ExcelJS anchors take. Excel draws a column `w` characters wide as
 * `w * 7 + 5` px (Calibri 11); an unset column defaults to 8.43 characters.
 */
function pixelToColumn(ws: Worksheet, x: number): number {
  let left = 0;
  for (let col = 1; col <= 200; col++) {
    const width = Math.floor((ws.getColumn(col).width ?? 8.43) * 7 + 5);
    if (x < left + width) return col - 1 + (x - left) / width;
    left += width;
  }
  return 200;
}

/**
 * Draws the footer at the current cursor (a blank separator row, the two
 * "Prepared by" / "Noted by" rows, the italic system-generated note, and the
 * logo anchored a couple of rows below) onto `ws`.
 *
 * Takes `wb` too: ExcelJS registers an image's bytes on the WORKBOOK
 * (`Workbook.addImage`, returning an id) and only then anchors that id on a
 * worksheet (`Worksheet.addImage`) — one registration per call, so a
 * multi-sheet report (SF2, MOSY) that calls this once per sheet embeds the
 * same bytes again for each sheet rather than sharing one image across
 * sheets, which ExcelJS does not support.
 *
 * The anchor is a fixed pixel `ext` (`ImagePosition`, not a cell RANGE), so
 * the image can never stretch or shift a column/row width the table above it
 * depends on.
 */
export function writeSheetFooter(wb: Workbook, ws: Worksheet, footer: ReportFooter): void {
  ws.addRow([]);
  const preparedRow = ws.addRow(["Prepared by:", footer.preparedBy]);
  preparedRow.getCell(1).font = { bold: true };
  const notedRow = ws.addRow(["Noted by:", footer.notedBy]);
  notedRow.getCell(1).font = { bold: true };
  const noteRow = ws.addRow([SYSTEM_GENERATED_NOTE]);
  noteRow.font = { italic: true, color: { argb: "FF666666" } };
  // Two blank rows of clearance so the logos never overlap the note line
  // above them, then the logos anchored left to right in that space.
  const logoAnchorRow = ws.rowCount; // 0-based index of the row after the note
  ws.addRow([]);
  ws.addRow([]);

  const ids = footerLogoIds(wb);
  let x = 0;
  FOOTER_LOGO_BUFFERS.forEach((logo, i) => {
    ws.addImage(ids[i]!, {
      tl: { col: pixelToColumn(ws, x), row: logoAnchorRow },
      ext: { width: logo.width, height: FOOTER_LOGO_HEIGHT },
    });
    x += logo.width + FOOTER_LOGO_GAP;
  });
}
