import "server-only";
import { prisma } from "@/lib/prisma";

/**
 * Hard-delete one school and everything recorded under it.
 *
 * This is the only place in the app that removes rows instead of setting
 * `deletedAt`, and it is safe for exactly one reason: the caller has already
 * confirmed `School.isDemo` is true, so the target holds training data that was
 * generated by this app and nothing else. Never call it with a real school id.
 *
 * Why an explicit ordered list rather than `prisma.school.delete()`:
 * `Enrollment.school` and `Learner.school` are required relations declared
 * without `onDelete: Cascade`, so Postgres restricts the parent delete, and
 * `User.school` is optional and therefore `SetNull` — a plain cascade would
 * abort on the first and orphan School Head accounts on the second. The order
 * below is the reverse of `SNAPSHOT_MODELS` in `src/lib/db/schema-order.ts`,
 * for the same reason that list exists: a child must go before its parent.
 *
 * Ids are collected up front and every delete is keyed on `in: [...]` rather
 * than on a nested relation filter, so each statement's blast radius is a
 * literal list of rows belonging to this school — not a join whose predicate
 * could be misread.
 *
 * @returns the number of rows removed, per model, for the audit metadata.
 */
export async function deleteSchoolCompletely(
  schoolId: string
): Promise<{ authIds: string[]; counts: Record<string, number> }> {
  const [learners, users, sections] = await Promise.all([
    prisma.learner.findMany({ where: { schoolId }, select: { id: true } }),
    prisma.user.findMany({ where: { schoolId }, select: { id: true, authId: true } }),
    prisma.section.findMany({ where: { schoolId }, select: { id: true } }),
  ]);
  const gradeLevels = await prisma.gradeLevel.findMany({
    where: { schoolId },
    select: { id: true },
  });

  const learnerIds = learners.map((l) => l.id);
  const userIds = users.map((u) => u.id);
  const sectionIds = sections.map((s) => s.id);
  const gradeLevelIds = gradeLevels.map((g) => g.id);

  const counts: Record<string, number> = {};
  const record = (model: string, n: number) => {
    if (n > 0) counts[model] = n;
  };

  await prisma.$transaction(async (tx) => {
    // Records about learners.
    record("termGrade", (await tx.termGrade.deleteMany({ where: { learnerId: { in: learnerIds } } })).count);
    record(
      "readingLevelRecord",
      (await tx.readingLevelRecord.deleteMany({ where: { learnerId: { in: learnerIds } } })).count
    );
    record("attendance", (await tx.attendance.deleteMany({ where: { learnerId: { in: learnerIds } } })).count);
    record(
      "attendanceDayMeta",
      (await tx.attendanceDayMeta.deleteMany({ where: { gradeLevelId: { in: gradeLevelIds } } })).count
    );
    record("aralProfile", (await tx.aralProfile.deleteMany({ where: { learnerId: { in: learnerIds } } })).count);
    record("enrollment", (await tx.enrollment.deleteMany({ where: { schoolId } })).count);
    record("learner", (await tx.learner.deleteMany({ where: { schoolId } })).count);

    // School-scoped content and the support queue. Notification and UnlockGrant
    // both point at SupportTicket, so they go first.
    record("notification", (await tx.notification.deleteMany({ where: { schoolId } })).count);
    record("unlockGrant", (await tx.unlockGrant.deleteMany({ where: { schoolId } })).count);
    record("supportTicket", (await tx.supportTicket.deleteMany({ where: { schoolId } })).count);
    record("report", (await tx.report.deleteMany({ where: { schoolId } })).count);
    record("announcement", (await tx.announcement.deleteMany({ where: { schoolId } })).count);
    record("teacherInvite", (await tx.teacherInvite.deleteMany({ where: { schoolId } })).count);

    // People. `User.advisorySectionId` is a real FK to Section, so the pointer
    // is cleared before Section is deleted — the same trap schema-order.ts warns
    // about, in the delete direction.
    record("teacherSection", (await tx.teacherSection.deleteMany({ where: { teacherId: { in: userIds } } })).count);
    record("teacherProfile", (await tx.teacherProfile.deleteMany({ where: { userId: { in: userIds } } })).count);
    record(
      "schoolHeadProfile",
      (await tx.schoolHeadProfile.deleteMany({ where: { userId: { in: userIds } } })).count
    );
    await tx.user.updateMany({
      where: { id: { in: userIds } },
      data: { advisorySectionId: null },
    });
    record("user", (await tx.user.deleteMany({ where: { id: { in: userIds } } })).count);

    // Structure, innermost first.
    record("section", (await tx.section.deleteMany({ where: { id: { in: sectionIds } } })).count);
    record("gradeLevel", (await tx.gradeLevel.deleteMany({ where: { schoolId } })).count);
    record("schoolYear", (await tx.schoolYear.deleteMany({ where: { schoolId } })).count);
    await tx.school.delete({ where: { id: schoolId } });
    record("school", 1);
  });

  // Audit rows are kept on purpose: they are the record that a Super Admin ran
  // this teardown, and `AuditLog.schoolId` is a plain nullable column with no
  // foreign key, so nothing forces their removal.

  return { authIds: users.map((u) => u.authId), counts };
}
