import { describe, it, expect } from "vitest";
import type { ParsedSchoolRow } from "@/lib/import/school-roster";
import { assignSchoolCredentials, PLACEHOLDER_SCHOOL_ID } from "@/lib/import/school-credentials";
import { defaultSchoolHeadPassword } from "@/lib/auth/school-head-password";

function row(sourceRow: number, schoolIdCode: string | null, name: string): ParsedSchoolRow {
  return { sourceRow, schoolIdCode, rawSchoolId: schoolIdCode ?? "", name, district: "Malapatan 2" };
}

describe("defaultSchoolHeadPassword", () => {
  it("is the School ID itself for a school with no extension suffix", () => {
    expect(defaultSchoolHeadPassword("130554")).toBe("130554");
  });

  it("drops the extension suffix, so a school and its extensions share one default", () => {
    expect(defaultSchoolHeadPassword("130554-2")).toBe("130554");
    expect(defaultSchoolHeadPassword("130554-3")).toBe("130554");
    expect(defaultSchoolHeadPassword("502694-12")).toBe("502694");
  });

  it("drops the suffix from the no-ID placeholder group too", () => {
    expect(defaultSchoolHeadPassword(`${PLACEHOLDER_SCHOOL_ID}-2`)).toBe(PLACEHOLDER_SCHOOL_ID);
  });

  it("leaves a code alone unless the part before the dash is a six-digit DepEd id", () => {
    // Typed by an admin, not generated by the import: stripping these would hand
    // out a password nobody set.
    expect(defaultSchoolHeadPassword("SCHOOL-1")).toBe("SCHOOL-1");
    expect(defaultSchoolHeadPassword("1305540-2")).toBe("1305540-2");
    expect(defaultSchoolHeadPassword("13055-2")).toBe("13055-2");
    expect(defaultSchoolHeadPassword("130554-A")).toBe("130554-A");
    expect(defaultSchoolHeadPassword("130554-")).toBe("130554-");
  });

  it("recovers exactly the password the roster import gave every school in a collision group", () => {
    // The import is the forward rule (bare id -> stored code); this is its inverse.
    // If either side changes its suffix shape, this is the test that says so.
    const { assignments } = assignSchoolCredentials([
      row(299, "130554", "Naidas T. Opong ES"),
      row(300, "130554", "Naidas T. Opong ES (Banlas Extension)"),
      row(301, "130554", "Naidas T. Opong ES (Litos Extension)"),
      row(280, "130551", "Del Hilado ES"),
      row(281, "130551", "Del Hilado ES (Matlusi Extension)"),
      row(10, "502694", "A"),
      row(11, "502694", "B"),
      row(147, null, "Datal Bong ES - Green Valley extension"),
      row(306, null, "Nabol NHS (Proposed)"),
      row(7, "500282", "Alabel Integrated SPED Center"),
    ]);
    expect(assignments.some((a) => a.suffixed)).toBe(true);
    for (const a of assignments) {
      expect(defaultSchoolHeadPassword(a.schoolIdCode)).toBe(a.password);
    }
  });
});
